FROM mcr.microsoft.com/devcontainers/base:ubuntu

LABEL devcontainer.metadata="[{\"containerEnv\":{\"IMAGE_VALUE\":\"image-metadata\",\"REPOSITORY_VALUE\":\"image\"},\"onCreateCommand\":{\"image\":\"printf image > /workspace/.image-on-create\"}}]"
