// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: agent/v1/service.proto

package agentv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "gitea.dev/codespace/internal/rpc/agent/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AgentControlServiceName is the fully-qualified name of the AgentControlService service.
	AgentControlServiceName = "agent.v1.AgentControlService"
	// AgentAccessServiceName is the fully-qualified name of the AgentAccessService service.
	AgentAccessServiceName = "agent.v1.AgentAccessService"
	// RuntimeEndpointServiceName is the fully-qualified name of the RuntimeEndpointService service.
	RuntimeEndpointServiceName = "agent.v1.RuntimeEndpointService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AgentControlServiceControlProcedure is the fully-qualified name of the AgentControlService's
	// Control RPC.
	AgentControlServiceControlProcedure = "/agent.v1.AgentControlService/Control"
	// AgentControlServiceUploadLogsProcedure is the fully-qualified name of the AgentControlService's
	// UploadLogs RPC.
	AgentControlServiceUploadLogsProcedure = "/agent.v1.AgentControlService/UploadLogs"
	// AgentAccessServiceAccessProcedure is the fully-qualified name of the AgentAccessService's Access
	// RPC.
	AgentAccessServiceAccessProcedure = "/agent.v1.AgentAccessService/Access"
	// RuntimeEndpointServiceListProcedure is the fully-qualified name of the RuntimeEndpointService's
	// List RPC.
	RuntimeEndpointServiceListProcedure = "/agent.v1.RuntimeEndpointService/List"
	// RuntimeEndpointServiceSetProcedure is the fully-qualified name of the RuntimeEndpointService's
	// Set RPC.
	RuntimeEndpointServiceSetProcedure = "/agent.v1.RuntimeEndpointService/Set"
	// RuntimeEndpointServiceDeleteProcedure is the fully-qualified name of the RuntimeEndpointService's
	// Delete RPC.
	RuntimeEndpointServiceDeleteProcedure = "/agent.v1.RuntimeEndpointService/Delete"
)

// AgentControlServiceClient is a client for the agent.v1.AgentControlService service.
type AgentControlServiceClient interface {
	// Control resumes a session by reporting facts before accepting new execution.
	Control(context.Context) *connect.BidiStreamForClient[v1.ControlRequest, v1.ControlResponse]
	// UploadLogs forwards an immutable batch at Gitea's acknowledged byte offset.
	UploadLogs(context.Context, *connect.Request[v1.UploadLogsRequest]) (*connect.Response[v1.UploadLogsResponse], error)
}

// NewAgentControlServiceClient constructs a client for the agent.v1.AgentControlService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentControlServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentControlServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentControlServiceMethods := v1.File_agent_v1_service_proto.Services().ByName("AgentControlService").Methods()
	return &agentControlServiceClient{
		control: connect.NewClient[v1.ControlRequest, v1.ControlResponse](
			httpClient,
			baseURL+AgentControlServiceControlProcedure,
			connect.WithSchema(agentControlServiceMethods.ByName("Control")),
			connect.WithClientOptions(opts...),
		),
		uploadLogs: connect.NewClient[v1.UploadLogsRequest, v1.UploadLogsResponse](
			httpClient,
			baseURL+AgentControlServiceUploadLogsProcedure,
			connect.WithSchema(agentControlServiceMethods.ByName("UploadLogs")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentControlServiceClient implements AgentControlServiceClient.
type agentControlServiceClient struct {
	control    *connect.Client[v1.ControlRequest, v1.ControlResponse]
	uploadLogs *connect.Client[v1.UploadLogsRequest, v1.UploadLogsResponse]
}

// Control calls agent.v1.AgentControlService.Control.
func (c *agentControlServiceClient) Control(ctx context.Context) *connect.BidiStreamForClient[v1.ControlRequest, v1.ControlResponse] {
	return c.control.CallBidiStream(ctx)
}

// UploadLogs calls agent.v1.AgentControlService.UploadLogs.
func (c *agentControlServiceClient) UploadLogs(ctx context.Context, req *connect.Request[v1.UploadLogsRequest]) (*connect.Response[v1.UploadLogsResponse], error) {
	return c.uploadLogs.CallUnary(ctx, req)
}

// AgentControlServiceHandler is an implementation of the agent.v1.AgentControlService service.
type AgentControlServiceHandler interface {
	// Control resumes a session by reporting facts before accepting new execution.
	Control(context.Context, *connect.BidiStream[v1.ControlRequest, v1.ControlResponse]) error
	// UploadLogs forwards an immutable batch at Gitea's acknowledged byte offset.
	UploadLogs(context.Context, *connect.Request[v1.UploadLogsRequest]) (*connect.Response[v1.UploadLogsResponse], error)
}

// NewAgentControlServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentControlServiceHandler(svc AgentControlServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentControlServiceMethods := v1.File_agent_v1_service_proto.Services().ByName("AgentControlService").Methods()
	agentControlServiceControlHandler := connect.NewBidiStreamHandler(
		AgentControlServiceControlProcedure,
		svc.Control,
		connect.WithSchema(agentControlServiceMethods.ByName("Control")),
		connect.WithHandlerOptions(opts...),
	)
	agentControlServiceUploadLogsHandler := connect.NewUnaryHandler(
		AgentControlServiceUploadLogsProcedure,
		svc.UploadLogs,
		connect.WithSchema(agentControlServiceMethods.ByName("UploadLogs")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agent.v1.AgentControlService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentControlServiceControlProcedure:
			agentControlServiceControlHandler.ServeHTTP(w, r)
		case AgentControlServiceUploadLogsProcedure:
			agentControlServiceUploadLogsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentControlServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentControlServiceHandler struct{}

func (UnimplementedAgentControlServiceHandler) Control(context.Context, *connect.BidiStream[v1.ControlRequest, v1.ControlResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("agent.v1.AgentControlService.Control is not implemented"))
}

func (UnimplementedAgentControlServiceHandler) UploadLogs(context.Context, *connect.Request[v1.UploadLogsRequest]) (*connect.Response[v1.UploadLogsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agent.v1.AgentControlService.UploadLogs is not implemented"))
}

// AgentAccessServiceClient is a client for the agent.v1.AgentAccessService service.
type AgentAccessServiceClient interface {
	// Access requires an accepted opening frame before transferring user data.
	Access(context.Context) *connect.BidiStreamForClient[v1.AccessRequest, v1.AccessResponse]
}

// NewAgentAccessServiceClient constructs a client for the agent.v1.AgentAccessService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentAccessServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentAccessServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentAccessServiceMethods := v1.File_agent_v1_service_proto.Services().ByName("AgentAccessService").Methods()
	return &agentAccessServiceClient{
		access: connect.NewClient[v1.AccessRequest, v1.AccessResponse](
			httpClient,
			baseURL+AgentAccessServiceAccessProcedure,
			connect.WithSchema(agentAccessServiceMethods.ByName("Access")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentAccessServiceClient implements AgentAccessServiceClient.
type agentAccessServiceClient struct {
	access *connect.Client[v1.AccessRequest, v1.AccessResponse]
}

// Access calls agent.v1.AgentAccessService.Access.
func (c *agentAccessServiceClient) Access(ctx context.Context) *connect.BidiStreamForClient[v1.AccessRequest, v1.AccessResponse] {
	return c.access.CallBidiStream(ctx)
}

// AgentAccessServiceHandler is an implementation of the agent.v1.AgentAccessService service.
type AgentAccessServiceHandler interface {
	// Access requires an accepted opening frame before transferring user data.
	Access(context.Context, *connect.BidiStream[v1.AccessRequest, v1.AccessResponse]) error
}

// NewAgentAccessServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentAccessServiceHandler(svc AgentAccessServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentAccessServiceMethods := v1.File_agent_v1_service_proto.Services().ByName("AgentAccessService").Methods()
	agentAccessServiceAccessHandler := connect.NewBidiStreamHandler(
		AgentAccessServiceAccessProcedure,
		svc.Access,
		connect.WithSchema(agentAccessServiceMethods.ByName("Access")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agent.v1.AgentAccessService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentAccessServiceAccessProcedure:
			agentAccessServiceAccessHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentAccessServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentAccessServiceHandler struct{}

func (UnimplementedAgentAccessServiceHandler) Access(context.Context, *connect.BidiStream[v1.AccessRequest, v1.AccessResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("agent.v1.AgentAccessService.Access is not implemented"))
}

// RuntimeEndpointServiceClient is a client for the agent.v1.RuntimeEndpointService service.
type RuntimeEndpointServiceClient interface {
	// List returns the HTTP endpoints currently published by this runtime.
	List(context.Context, *connect.Request[v1.RuntimeEndpointServiceListRequest]) (*connect.Response[v1.RuntimeEndpointServiceListResponse], error)
	// Set adds or replaces one endpoint and durably publishes the new target.
	Set(context.Context, *connect.Request[v1.RuntimeEndpointServiceSetRequest]) (*connect.Response[v1.RuntimeEndpointServiceSetResponse], error)
	// Delete removes one endpoint and durably publishes the new target.
	Delete(context.Context, *connect.Request[v1.RuntimeEndpointServiceDeleteRequest]) (*connect.Response[v1.RuntimeEndpointServiceDeleteResponse], error)
}

// NewRuntimeEndpointServiceClient constructs a client for the agent.v1.RuntimeEndpointService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRuntimeEndpointServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RuntimeEndpointServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	runtimeEndpointServiceMethods := v1.File_agent_v1_service_proto.Services().ByName("RuntimeEndpointService").Methods()
	return &runtimeEndpointServiceClient{
		list: connect.NewClient[v1.RuntimeEndpointServiceListRequest, v1.RuntimeEndpointServiceListResponse](
			httpClient,
			baseURL+RuntimeEndpointServiceListProcedure,
			connect.WithSchema(runtimeEndpointServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		set: connect.NewClient[v1.RuntimeEndpointServiceSetRequest, v1.RuntimeEndpointServiceSetResponse](
			httpClient,
			baseURL+RuntimeEndpointServiceSetProcedure,
			connect.WithSchema(runtimeEndpointServiceMethods.ByName("Set")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[v1.RuntimeEndpointServiceDeleteRequest, v1.RuntimeEndpointServiceDeleteResponse](
			httpClient,
			baseURL+RuntimeEndpointServiceDeleteProcedure,
			connect.WithSchema(runtimeEndpointServiceMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
	}
}

// runtimeEndpointServiceClient implements RuntimeEndpointServiceClient.
type runtimeEndpointServiceClient struct {
	list   *connect.Client[v1.RuntimeEndpointServiceListRequest, v1.RuntimeEndpointServiceListResponse]
	set    *connect.Client[v1.RuntimeEndpointServiceSetRequest, v1.RuntimeEndpointServiceSetResponse]
	delete *connect.Client[v1.RuntimeEndpointServiceDeleteRequest, v1.RuntimeEndpointServiceDeleteResponse]
}

// List calls agent.v1.RuntimeEndpointService.List.
func (c *runtimeEndpointServiceClient) List(ctx context.Context, req *connect.Request[v1.RuntimeEndpointServiceListRequest]) (*connect.Response[v1.RuntimeEndpointServiceListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// Set calls agent.v1.RuntimeEndpointService.Set.
func (c *runtimeEndpointServiceClient) Set(ctx context.Context, req *connect.Request[v1.RuntimeEndpointServiceSetRequest]) (*connect.Response[v1.RuntimeEndpointServiceSetResponse], error) {
	return c.set.CallUnary(ctx, req)
}

// Delete calls agent.v1.RuntimeEndpointService.Delete.
func (c *runtimeEndpointServiceClient) Delete(ctx context.Context, req *connect.Request[v1.RuntimeEndpointServiceDeleteRequest]) (*connect.Response[v1.RuntimeEndpointServiceDeleteResponse], error) {
	return c.delete.CallUnary(ctx, req)
}

// RuntimeEndpointServiceHandler is an implementation of the agent.v1.RuntimeEndpointService
// service.
type RuntimeEndpointServiceHandler interface {
	// List returns the HTTP endpoints currently published by this runtime.
	List(context.Context, *connect.Request[v1.RuntimeEndpointServiceListRequest]) (*connect.Response[v1.RuntimeEndpointServiceListResponse], error)
	// Set adds or replaces one endpoint and durably publishes the new target.
	Set(context.Context, *connect.Request[v1.RuntimeEndpointServiceSetRequest]) (*connect.Response[v1.RuntimeEndpointServiceSetResponse], error)
	// Delete removes one endpoint and durably publishes the new target.
	Delete(context.Context, *connect.Request[v1.RuntimeEndpointServiceDeleteRequest]) (*connect.Response[v1.RuntimeEndpointServiceDeleteResponse], error)
}

// NewRuntimeEndpointServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRuntimeEndpointServiceHandler(svc RuntimeEndpointServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	runtimeEndpointServiceMethods := v1.File_agent_v1_service_proto.Services().ByName("RuntimeEndpointService").Methods()
	runtimeEndpointServiceListHandler := connect.NewUnaryHandler(
		RuntimeEndpointServiceListProcedure,
		svc.List,
		connect.WithSchema(runtimeEndpointServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	runtimeEndpointServiceSetHandler := connect.NewUnaryHandler(
		RuntimeEndpointServiceSetProcedure,
		svc.Set,
		connect.WithSchema(runtimeEndpointServiceMethods.ByName("Set")),
		connect.WithHandlerOptions(opts...),
	)
	runtimeEndpointServiceDeleteHandler := connect.NewUnaryHandler(
		RuntimeEndpointServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(runtimeEndpointServiceMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agent.v1.RuntimeEndpointService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RuntimeEndpointServiceListProcedure:
			runtimeEndpointServiceListHandler.ServeHTTP(w, r)
		case RuntimeEndpointServiceSetProcedure:
			runtimeEndpointServiceSetHandler.ServeHTTP(w, r)
		case RuntimeEndpointServiceDeleteProcedure:
			runtimeEndpointServiceDeleteHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRuntimeEndpointServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRuntimeEndpointServiceHandler struct{}

func (UnimplementedRuntimeEndpointServiceHandler) List(context.Context, *connect.Request[v1.RuntimeEndpointServiceListRequest]) (*connect.Response[v1.RuntimeEndpointServiceListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agent.v1.RuntimeEndpointService.List is not implemented"))
}

func (UnimplementedRuntimeEndpointServiceHandler) Set(context.Context, *connect.Request[v1.RuntimeEndpointServiceSetRequest]) (*connect.Response[v1.RuntimeEndpointServiceSetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agent.v1.RuntimeEndpointService.Set is not implemented"))
}

func (UnimplementedRuntimeEndpointServiceHandler) Delete(context.Context, *connect.Request[v1.RuntimeEndpointServiceDeleteRequest]) (*connect.Response[v1.RuntimeEndpointServiceDeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agent.v1.RuntimeEndpointService.Delete is not implemented"))
}
