// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: component/v1/service.proto

package componentv1

import (
	v1 "gitea.dev/codespace/internal/rpc/agent/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GatewayControlRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	SessionId       string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Sequence        uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ActiveSessions  map[string]int64       `protobuf:"bytes,4,rep,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GatewayControlRequest) Reset() {
	*x = GatewayControlRequest{}
	mi := &file_component_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayControlRequest) ProtoMessage() {}

func (x *GatewayControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_component_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayControlRequest.ProtoReflect.Descriptor instead.
func (*GatewayControlRequest) Descriptor() ([]byte, []int) {
	return file_component_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *GatewayControlRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *GatewayControlRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GatewayControlRequest) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *GatewayControlRequest) GetActiveSessions() map[string]int64 {
	if x != nil {
		return x.ActiveSessions
	}
	return nil
}

type GatewayControlResponse struct {
	state                      protoimpl.MessageState        `protogen:"open.v1"`
	ProtocolVersion            uint32                        `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Sequence                   uint64                        `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	PermitValidForMilliseconds int64                         `protobuf:"varint,3,opt,name=permit_valid_for_milliseconds,json=permitValidForMilliseconds,proto3" json:"permit_valid_for_milliseconds,omitempty"`
	Cursor                     string                        `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Snapshot                   bool                          `protobuf:"varint,5,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Config                     *GatewayConfigurationSnapshot `protobuf:"bytes,6,opt,name=config,proto3" json:"config,omitempty"`
	Runtimes                   []*GatewayRuntimeRoute        `protobuf:"bytes,7,rep,name=runtimes,proto3" json:"runtimes,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *GatewayControlResponse) Reset() {
	*x = GatewayControlResponse{}
	mi := &file_component_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayControlResponse) ProtoMessage() {}

func (x *GatewayControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_component_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayControlResponse.ProtoReflect.Descriptor instead.
func (*GatewayControlResponse) Descriptor() ([]byte, []int) {
	return file_component_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayControlResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *GatewayControlResponse) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *GatewayControlResponse) GetPermitValidForMilliseconds() int64 {
	if x != nil {
		return x.PermitValidForMilliseconds
	}
	return 0
}

func (x *GatewayControlResponse) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *GatewayControlResponse) GetSnapshot() bool {
	if x != nil {
		return x.Snapshot
	}
	return false
}

func (x *GatewayControlResponse) GetConfig() *GatewayConfigurationSnapshot {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GatewayControlResponse) GetRuntimes() []*GatewayRuntimeRoute {
	if x != nil {
		return x.Runtimes
	}
	return nil
}

type GatewayConfigurationSnapshot struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	HttpListen                     string                 `protobuf:"bytes,1,opt,name=http_listen,json=httpListen,proto3" json:"http_listen,omitempty"`
	PublicUrl                      string                 `protobuf:"bytes,2,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	SshListen                      string                 `protobuf:"bytes,3,opt,name=ssh_listen,json=sshListen,proto3" json:"ssh_listen,omitempty"`
	SshPublicAddress               string                 `protobuf:"bytes,4,opt,name=ssh_public_address,json=sshPublicAddress,proto3" json:"ssh_public_address,omitempty"`
	SessionTtlMilliseconds         int64                  `protobuf:"varint,5,opt,name=session_ttl_milliseconds,json=sessionTtlMilliseconds,proto3" json:"session_ttl_milliseconds,omitempty"`
	SessionIdleTimeoutMilliseconds int64                  `protobuf:"varint,6,opt,name=session_idle_timeout_milliseconds,json=sessionIdleTimeoutMilliseconds,proto3" json:"session_idle_timeout_milliseconds,omitempty"`
	RevalidateIntervalMilliseconds int64                  `protobuf:"varint,7,opt,name=revalidate_interval_milliseconds,json=revalidateIntervalMilliseconds,proto3" json:"revalidate_interval_milliseconds,omitempty"`
	MaxSessionsPerCodespace        int32                  `protobuf:"varint,8,opt,name=max_sessions_per_codespace,json=maxSessionsPerCodespace,proto3" json:"max_sessions_per_codespace,omitempty"`
	MaxSessionsPerUser             int32                  `protobuf:"varint,9,opt,name=max_sessions_per_user,json=maxSessionsPerUser,proto3" json:"max_sessions_per_user,omitempty"`
	MaxInflight                    int32                  `protobuf:"varint,10,opt,name=max_inflight,json=maxInflight,proto3" json:"max_inflight,omitempty"`
	MaxInflightPerSession          int32                  `protobuf:"varint,11,opt,name=max_inflight_per_session,json=maxInflightPerSession,proto3" json:"max_inflight_per_session,omitempty"`
	MaxChannelsPerSshConnection    int32                  `protobuf:"varint,12,opt,name=max_channels_per_ssh_connection,json=maxChannelsPerSshConnection,proto3" json:"max_channels_per_ssh_connection,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *GatewayConfigurationSnapshot) Reset() {
	*x = GatewayConfigurationSnapshot{}
	mi := &file_component_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayConfigurationSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayConfigurationSnapshot) ProtoMessage() {}

func (x *GatewayConfigurationSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_component_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayConfigurationSnapshot.ProtoReflect.Descriptor instead.
func (*GatewayConfigurationSnapshot) Descriptor() ([]byte, []int) {
	return file_component_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *GatewayConfigurationSnapshot) GetHttpListen() string {
	if x != nil {
		return x.HttpListen
	}
	return ""
}

func (x *GatewayConfigurationSnapshot) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

func (x *GatewayConfigurationSnapshot) GetSshListen() string {
	if x != nil {
		return x.SshListen
	}
	return ""
}

func (x *GatewayConfigurationSnapshot) GetSshPublicAddress() string {
	if x != nil {
		return x.SshPublicAddress
	}
	return ""
}

func (x *GatewayConfigurationSnapshot) GetSessionTtlMilliseconds() int64 {
	if x != nil {
		return x.SessionTtlMilliseconds
	}
	return 0
}

func (x *GatewayConfigurationSnapshot) GetSessionIdleTimeoutMilliseconds() int64 {
	if x != nil {
		return x.SessionIdleTimeoutMilliseconds
	}
	return 0
}

func (x *GatewayConfigurationSnapshot) GetRevalidateIntervalMilliseconds() int64 {
	if x != nil {
		return x.RevalidateIntervalMilliseconds
	}
	return 0
}

func (x *GatewayConfigurationSnapshot) GetMaxSessionsPerCodespace() int32 {
	if x != nil {
		return x.MaxSessionsPerCodespace
	}
	return 0
}

func (x *GatewayConfigurationSnapshot) GetMaxSessionsPerUser() int32 {
	if x != nil {
		return x.MaxSessionsPerUser
	}
	return 0
}

func (x *GatewayConfigurationSnapshot) GetMaxInflight() int32 {
	if x != nil {
		return x.MaxInflight
	}
	return 0
}

func (x *GatewayConfigurationSnapshot) GetMaxInflightPerSession() int32 {
	if x != nil {
		return x.MaxInflightPerSession
	}
	return 0
}

func (x *GatewayConfigurationSnapshot) GetMaxChannelsPerSshConnection() int32 {
	if x != nil {
		return x.MaxChannelsPerSshConnection
	}
	return 0
}

type GatewayRuntimeRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteUid       string                 `protobuf:"bytes,1,opt,name=site_uid,json=siteUid,proto3" json:"site_uid,omitempty"`
	ResourceUid   string                 `protobuf:"bytes,2,opt,name=resource_uid,json=resourceUid,proto3" json:"resource_uid,omitempty"`
	RuntimeUuid   string                 `protobuf:"bytes,3,opt,name=runtime_uuid,json=runtimeUuid,proto3" json:"runtime_uuid,omitempty"`
	PodUid        string                 `protobuf:"bytes,4,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	AgentAddress  string                 `protobuf:"bytes,5,opt,name=agent_address,json=agentAddress,proto3" json:"agent_address,omitempty"`
	TargetVersion int64                  `protobuf:"varint,6,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	Endpoints     []*GatewayEndpoint     `protobuf:"bytes,7,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	GiteaWebUrl   string                 `protobuf:"bytes,8,opt,name=gitea_web_url,json=giteaWebUrl,proto3" json:"gitea_web_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayRuntimeRoute) Reset() {
	*x = GatewayRuntimeRoute{}
	mi := &file_component_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayRuntimeRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayRuntimeRoute) ProtoMessage() {}

func (x *GatewayRuntimeRoute) ProtoReflect() protoreflect.Message {
	mi := &file_component_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayRuntimeRoute.ProtoReflect.Descriptor instead.
func (*GatewayRuntimeRoute) Descriptor() ([]byte, []int) {
	return file_component_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *GatewayRuntimeRoute) GetSiteUid() string {
	if x != nil {
		return x.SiteUid
	}
	return ""
}

func (x *GatewayRuntimeRoute) GetResourceUid() string {
	if x != nil {
		return x.ResourceUid
	}
	return ""
}

func (x *GatewayRuntimeRoute) GetRuntimeUuid() string {
	if x != nil {
		return x.RuntimeUuid
	}
	return ""
}

func (x *GatewayRuntimeRoute) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *GatewayRuntimeRoute) GetAgentAddress() string {
	if x != nil {
		return x.AgentAddress
	}
	return ""
}

func (x *GatewayRuntimeRoute) GetTargetVersion() int64 {
	if x != nil {
		return x.TargetVersion
	}
	return 0
}

func (x *GatewayRuntimeRoute) GetEndpoints() []*GatewayEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *GatewayRuntimeRoute) GetGiteaWebUrl() string {
	if x != nil {
		return x.GiteaWebUrl
	}
	return ""
}

type GatewayEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Public        bool                   `protobuf:"varint,3,opt,name=public,proto3" json:"public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayEndpoint) Reset() {
	*x = GatewayEndpoint{}
	mi := &file_component_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayEndpoint) ProtoMessage() {}

func (x *GatewayEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_component_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayEndpoint.ProtoReflect.Descriptor instead.
func (*GatewayEndpoint) Descriptor() ([]byte, []int) {
	return file_component_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *GatewayEndpoint) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *GatewayEndpoint) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *GatewayEndpoint) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

type AuthorizeGatewayRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Types that are valid to be assigned to Request:
	//
	//	*AuthorizeGatewayRequest_OpenCode
	//	*AuthorizeGatewayRequest_PublicEndpoint
	//	*AuthorizeGatewayRequest_SshPublicKey
	//	*AuthorizeGatewayRequest_EndpointSession
	//	*AuthorizeGatewayRequest_SshSession
	Request       isAuthorizeGatewayRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeGatewayRequest) Reset() {
	*x = AuthorizeGatewayRequest{}
	mi := &file_component_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeGatewayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeGatewayRequest) ProtoMessage() {}

func (x *AuthorizeGatewayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_component_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeGatewayRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeGatewayRequest) Descriptor() ([]byte, []int) {
	return file_component_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *AuthorizeGatewayRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *AuthorizeGatewayRequest) GetRequest() isAuthorizeGatewayRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *AuthorizeGatewayRequest) GetOpenCode() *OpenCodeAuthorization {
	if x != nil {
		if x, ok := x.Request.(*AuthorizeGatewayRequest_OpenCode); ok {
			return x.OpenCode
		}
	}
	return nil
}

func (x *AuthorizeGatewayRequest) GetPublicEndpoint() *PublicEndpointAuthorization {
	if x != nil {
		if x, ok := x.Request.(*AuthorizeGatewayRequest_PublicEndpoint); ok {
			return x.PublicEndpoint
		}
	}
	return nil
}

func (x *AuthorizeGatewayRequest) GetSshPublicKey() *SSHPublicKeyAuthorization {
	if x != nil {
		if x, ok := x.Request.(*AuthorizeGatewayRequest_SshPublicKey); ok {
			return x.SshPublicKey
		}
	}
	return nil
}

func (x *AuthorizeGatewayRequest) GetEndpointSession() *EndpointSessionAuthorization {
	if x != nil {
		if x, ok := x.Request.(*AuthorizeGatewayRequest_EndpointSession); ok {
			return x.EndpointSession
		}
	}
	return nil
}

func (x *AuthorizeGatewayRequest) GetSshSession() *SSHSessionAuthorization {
	if x != nil {
		if x, ok := x.Request.(*AuthorizeGatewayRequest_SshSession); ok {
			return x.SshSession
		}
	}
	return nil
}

type isAuthorizeGatewayRequest_Request interface {
	isAuthorizeGatewayRequest_Request()
}

type AuthorizeGatewayRequest_OpenCode struct {
	OpenCode *OpenCodeAuthorization `protobuf:"bytes,2,opt,name=open_code,json=openCode,proto3,oneof"`
}

type AuthorizeGatewayRequest_PublicEndpoint struct {
	PublicEndpoint *PublicEndpointAuthorization `protobuf:"bytes,3,opt,name=public_endpoint,json=publicEndpoint,proto3,oneof"`
}

type AuthorizeGatewayRequest_SshPublicKey struct {
	SshPublicKey *SSHPublicKeyAuthorization `protobuf:"bytes,4,opt,name=ssh_public_key,json=sshPublicKey,proto3,oneof"`
}

type AuthorizeGatewayRequest_EndpointSession struct {
	EndpointSession *EndpointSessionAuthorization `protobuf:"bytes,5,opt,name=endpoint_session,json=endpointSession,proto3,oneof"`
}

type AuthorizeGatewayRequest_SshSession struct {
	SshSession *SSHSessionAuthorization `protobuf:"bytes,6,opt,name=ssh_session,json=sshSession,proto3,oneof"`
}

func (*AuthorizeGatewayRequest_OpenCode) isAuthorizeGatewayRequest_Request() {}

func (*AuthorizeGatewayRequest_PublicEndpoint) isAuthorizeGatewayRequest_Request() {}

func (*AuthorizeGatewayRequest_SshPublicKey) isAuthorizeGatewayRequest_Request() {}

func (*AuthorizeGatewayRequest_EndpointSession) isAuthorizeGatewayRequest_Request() {}

func (*AuthorizeGatewayRequest_SshSession) isAuthorizeGatewayRequest_Request() {}

type OpenCodeAuthorization struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// code is the one-time authorization code issued by Gitea.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// runtime_uuid and endpoint_id are parsed from the canonical Gateway host.
	RuntimeUuid   string `protobuf:"bytes,2,opt,name=runtime_uuid,json=runtimeUuid,proto3" json:"runtime_uuid,omitempty"`
	EndpointId    string `protobuf:"bytes,3,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenCodeAuthorization) Reset() {
	*x = OpenCodeAuthorization{}
	mi := &file_component_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenCodeAuthorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenCodeAuthorization) ProtoMessage() {}

func (x *OpenCodeAuthorization) ProtoReflect() protoreflect.Message {
	mi := &file_component_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenCodeAuthorization.ProtoReflect.Descriptor instead.
func (*OpenCodeAuthorization) Descriptor() ([]byte, []int) {
	return file_component_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *OpenCodeAuthorization) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *OpenCodeAuthorization) GetRuntimeUuid() string {
	if x != nil {
		return x.RuntimeUuid
	}
	return ""
}

func (x *OpenCodeAuthorization) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

type PublicEndpointAuthorization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeUuid   string                 `protobuf:"bytes,1,opt,name=runtime_uuid,json=runtimeUuid,proto3" json:"runtime_uuid,omitempty"`
	EndpointId    string                 `protobuf:"bytes,2,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicEndpointAuthorization) Reset() {
	*x = PublicEndpointAuthorization{}
	mi := &file_component_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicEndpointAuthorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicEndpointAuthorization) ProtoMessage() {}

func (x *PublicEndpointAuthorization) ProtoReflect() protoreflect.Message {
	mi := &file_component_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicEndpointAuthorization.ProtoReflect.Descriptor instead.
func (*PublicEndpointAuthorization) Descriptor() ([]byte, []int) {
	return file_component_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *PublicEndpointAuthorization) GetRuntimeUuid() string {
	if x != nil {
		return x.RuntimeUuid
	}
	return ""
}

func (x *PublicEndpointAuthorization) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

type SSHPublicKeyAuthorization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeUuid   string                 `protobuf:"bytes,1,opt,name=runtime_uuid,json=runtimeUuid,proto3" json:"runtime_uuid,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHPublicKeyAuthorization) Reset() {
	*x = SSHPublicKeyAuthorization{}
	mi := &file_component_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHPublicKeyAuthorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHPublicKeyAuthorization) ProtoMessage() {}

func (x *SSHPublicKeyAuthorization) ProtoReflect() protoreflect.Message {
	mi := &file_component_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHPublicKeyAuthorization.ProtoReflect.Descriptor instead.
func (*SSHPublicKeyAuthorization) Descriptor() ([]byte, []int) {
	return file_component_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *SSHPublicKeyAuthorization) GetRuntimeUuid() string {
	if x != nil {
		return x.RuntimeUuid
	}
	return ""
}

func (x *SSHPublicKeyAuthorization) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type EndpointSessionAuthorization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RuntimeUuid   string                 `protobuf:"bytes,2,opt,name=runtime_uuid,json=runtimeUuid,proto3" json:"runtime_uuid,omitempty"`
	EndpointId    string                 `protobuf:"bytes,3,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointSessionAuthorization) Reset() {
	*x = EndpointSessionAuthorization{}
	mi := &file_component_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointSessionAuthorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointSessionAuthorization) ProtoMessage() {}

func (x *EndpointSessionAuthorization) ProtoReflect() protoreflect.Message {
	mi := &file_component_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointSessionAuthorization.ProtoReflect.Descriptor instead.
func (*EndpointSessionAuthorization) Descriptor() ([]byte, []int) {
	return file_component_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *EndpointSessionAuthorization) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *EndpointSessionAuthorization) GetRuntimeUuid() string {
	if x != nil {
		return x.RuntimeUuid
	}
	return ""
}

func (x *EndpointSessionAuthorization) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

type SSHSessionAuthorization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RuntimeUuid   string                 `protobuf:"bytes,2,opt,name=runtime_uuid,json=runtimeUuid,proto3" json:"runtime_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHSessionAuthorization) Reset() {
	*x = SSHSessionAuthorization{}
	mi := &file_component_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHSessionAuthorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHSessionAuthorization) ProtoMessage() {}

func (x *SSHSessionAuthorization) ProtoReflect() protoreflect.Message {
	mi := &file_component_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHSessionAuthorization.ProtoReflect.Descriptor instead.
func (*SSHSessionAuthorization) Descriptor() ([]byte, []int) {
	return file_component_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *SSHSessionAuthorization) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SSHSessionAuthorization) GetRuntimeUuid() string {
	if x != nil {
		return x.RuntimeUuid
	}
	return ""
}

type AuthorizeGatewayResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Allowed        bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	DeniedCategory string                 `protobuf:"bytes,2,opt,name=denied_category,json=deniedCategory,proto3" json:"denied_category,omitempty"`
	UserId         int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RuntimeUuid    string                 `protobuf:"bytes,4,opt,name=runtime_uuid,json=runtimeUuid,proto3" json:"runtime_uuid,omitempty"`
	EndpointId     string                 `protobuf:"bytes,5,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthorizeGatewayResponse) Reset() {
	*x = AuthorizeGatewayResponse{}
	mi := &file_component_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeGatewayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeGatewayResponse) ProtoMessage() {}

func (x *AuthorizeGatewayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_component_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeGatewayResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeGatewayResponse) Descriptor() ([]byte, []int) {
	return file_component_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *AuthorizeGatewayResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *AuthorizeGatewayResponse) GetDeniedCategory() string {
	if x != nil {
		return x.DeniedCategory
	}
	return ""
}

func (x *AuthorizeGatewayResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AuthorizeGatewayResponse) GetRuntimeUuid() string {
	if x != nil {
		return x.RuntimeUuid
	}
	return ""
}

func (x *AuthorizeGatewayResponse) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

type IssueAgentAccessRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	RuntimeUuid     string                 `protobuf:"bytes,2,opt,name=runtime_uuid,json=runtimeUuid,proto3" json:"runtime_uuid,omitempty"`
	Capability      v1.AccessCapability    `protobuf:"varint,3,opt,name=capability,proto3,enum=agent.v1.AccessCapability" json:"capability,omitempty"`
	EndpointId      string                 `protobuf:"bytes,4,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IssueAgentAccessRequest) Reset() {
	*x = IssueAgentAccessRequest{}
	mi := &file_component_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueAgentAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueAgentAccessRequest) ProtoMessage() {}

func (x *IssueAgentAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_component_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueAgentAccessRequest.ProtoReflect.Descriptor instead.
func (*IssueAgentAccessRequest) Descriptor() ([]byte, []int) {
	return file_component_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *IssueAgentAccessRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *IssueAgentAccessRequest) GetRuntimeUuid() string {
	if x != nil {
		return x.RuntimeUuid
	}
	return ""
}

func (x *IssueAgentAccessRequest) GetCapability() v1.AccessCapability {
	if x != nil {
		return x.Capability
	}
	return v1.AccessCapability(0)
}

func (x *IssueAgentAccessRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

type IssueAgentAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runtime       *GatewayRuntimeRoute   `protobuf:"bytes,1,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Ticket        string                 `protobuf:"bytes,2,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueAgentAccessResponse) Reset() {
	*x = IssueAgentAccessResponse{}
	mi := &file_component_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueAgentAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueAgentAccessResponse) ProtoMessage() {}

func (x *IssueAgentAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_component_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueAgentAccessResponse.ProtoReflect.Descriptor instead.
func (*IssueAgentAccessResponse) Descriptor() ([]byte, []int) {
	return file_component_v1_service_proto_rawDescGZIP(), []int{13}
}

func (x *IssueAgentAccessResponse) GetRuntime() *GatewayRuntimeRoute {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *IssueAgentAccessResponse) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

type CacheControlRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	CacheId         string                 `protobuf:"bytes,2,opt,name=cache_id,json=cacheId,proto3" json:"cache_id,omitempty"`
	SessionId       string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Sequence        uint64                 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Status          *CacheStatus           `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	// Types that are valid to be assigned to Maintenance:
	//
	//	*CacheControlRequest_BeginGc
	//	*CacheControlRequest_CompleteGc
	Maintenance   isCacheControlRequest_Maintenance `protobuf_oneof:"maintenance"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheControlRequest) Reset() {
	*x = CacheControlRequest{}
	mi := &file_component_v1_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheControlRequest) ProtoMessage() {}

func (x *CacheControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_component_v1_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheControlRequest.ProtoReflect.Descriptor instead.
func (*CacheControlRequest) Descriptor() ([]byte, []int) {
	return file_component_v1_service_proto_rawDescGZIP(), []int{14}
}

func (x *CacheControlRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *CacheControlRequest) GetCacheId() string {
	if x != nil {
		return x.CacheId
	}
	return ""
}

func (x *CacheControlRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CacheControlRequest) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *CacheControlRequest) GetStatus() *CacheStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CacheControlRequest) GetMaintenance() isCacheControlRequest_Maintenance {
	if x != nil {
		return x.Maintenance
	}
	return nil
}

func (x *CacheControlRequest) GetBeginGc() *CacheGCRequest {
	if x != nil {
		if x, ok := x.Maintenance.(*CacheControlRequest_BeginGc); ok {
			return x.BeginGc
		}
	}
	return nil
}

func (x *CacheControlRequest) GetCompleteGc() *CacheGCComplete {
	if x != nil {
		if x, ok := x.Maintenance.(*CacheControlRequest_CompleteGc); ok {
			return x.CompleteGc
		}
	}
	return nil
}

type isCacheControlRequest_Maintenance interface {
	isCacheControlRequest_Maintenance()
}

type CacheControlRequest_BeginGc struct {
	BeginGc *CacheGCRequest `protobuf:"bytes,6,opt,name=begin_gc,json=beginGc,proto3,oneof"`
}

type CacheControlRequest_CompleteGc struct {
	CompleteGc *CacheGCComplete `protobuf:"bytes,7,opt,name=complete_gc,json=completeGc,proto3,oneof"`
}

func (*CacheControlRequest_BeginGc) isCacheControlRequest_Maintenance() {}

func (*CacheControlRequest_CompleteGc) isCacheControlRequest_Maintenance() {}

type CacheControlResponse struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion            uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Sequence                   uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	PermitValidForMilliseconds int64                  `protobuf:"varint,3,opt,name=permit_valid_for_milliseconds,json=permitValidForMilliseconds,proto3" json:"permit_valid_for_milliseconds,omitempty"`
	Config                     *CacheConfiguration    `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	GcGrant                    *CacheGCGrant          `protobuf:"bytes,5,opt,name=gc_grant,json=gcGrant,proto3" json:"gc_grant,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *CacheControlResponse) Reset() {
	*x = CacheControlResponse{}
	mi := &file_component_v1_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheControlResponse) ProtoMessage() {}

func (x *CacheControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_component_v1_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheControlResponse.ProtoReflect.Descriptor instead.
func (*CacheControlResponse) Descriptor() ([]byte, []int) {
	return file_component_v1_service_proto_rawDescGZIP(), []int{15}
}

func (x *CacheControlResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *CacheControlResponse) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *CacheControlResponse) GetPermitValidForMilliseconds() int64 {
	if x != nil {
		return x.PermitValidForMilliseconds
	}
	return 0
}

func (x *CacheControlResponse) GetConfig() *CacheConfiguration {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CacheControlResponse) GetGcGrant() *CacheGCGrant {
	if x != nil {
		return x.GcGrant
	}
	return nil
}

type CacheConfiguration struct {
	state                  protoimpl.MessageState                 `protogen:"open.v1"`
	Id                     string                                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                   string                                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Revision               int64                                  `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	Enabled                bool                                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Listen                 string                                 `protobuf:"bytes,5,opt,name=listen,proto3" json:"listen,omitempty"`
	PublicUrl              string                                 `protobuf:"bytes,6,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	Storage                *CacheStorageConfiguration             `protobuf:"bytes,7,opt,name=storage,proto3" json:"storage,omitempty"`
	MaxSize                string                                 `protobuf:"bytes,8,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	MaxAgeMilliseconds     int64                                  `protobuf:"varint,9,opt,name=max_age_milliseconds,json=maxAgeMilliseconds,proto3" json:"max_age_milliseconds,omitempty"`
	GcIntervalMilliseconds int64                                  `protobuf:"varint,10,opt,name=gc_interval_milliseconds,json=gcIntervalMilliseconds,proto3" json:"gc_interval_milliseconds,omitempty"`
	Upstreams              map[string]*CacheUpstreamConfiguration `protobuf:"bytes,11,rep,name=upstreams,proto3" json:"upstreams,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CacheConfiguration) Reset() {
	*x = CacheConfiguration{}
	mi := &file_component_v1_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheConfiguration) ProtoMessage() {}

func (x *CacheConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_component_v1_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheConfiguration.ProtoReflect.Descriptor instead.
func (*CacheConfiguration) Descriptor() ([]byte, []int) {
	return file_component_v1_service_proto_rawDescGZIP(), []int{16}
}

func (x *CacheConfiguration) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CacheConfiguration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CacheConfiguration) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *CacheConfiguration) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CacheConfiguration) GetListen() string {
	if x != nil {
		return x.Listen
	}
	return ""
}

func (x *CacheConfiguration) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

func (x *CacheConfiguration) GetStorage() *CacheStorageConfiguration {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *CacheConfiguration) GetMaxSize() string {
	if x != nil {
		return x.MaxSize
	}
	return ""
}

func (x *CacheConfiguration) GetMaxAgeMilliseconds() int64 {
	if x != nil {
		return x.MaxAgeMilliseconds
	}
	return 0
}

func (x *CacheConfiguration) GetGcIntervalMilliseconds() int64 {
	if x != nil {
		return x.GcIntervalMilliseconds
	}
	return 0
}

func (x *CacheConfiguration) GetUpstreams() map[string]*CacheUpstreamConfiguration {
	if x != nil {
		return x.Upstreams
	}
	return nil
}

type CacheStorageConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	MinFreeSpace  string                 `protobuf:"bytes,3,opt,name=min_free_space,json=minFreeSpace,proto3" json:"min_free_space,omitempty"`
	S3            *CacheS3Configuration  `protobuf:"bytes,4,opt,name=s3,proto3" json:"s3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheStorageConfiguration) Reset() {
	*x = CacheStorageConfiguration{}
	mi := &file_component_v1_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheStorageConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheStorageConfiguration) ProtoMessage() {}

func (x *CacheStorageConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_component_v1_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheStorageConfiguration.ProtoReflect.Descriptor instead.
func (*CacheStorageConfiguration) Descriptor() ([]byte, []int) {
	return file_component_v1_service_proto_rawDescGZIP(), []int{17}
}

func (x *CacheStorageConfiguration) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *CacheStorageConfiguration) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CacheStorageConfiguration) GetMinFreeSpace() string {
	if x != nil {
		return x.MinFreeSpace
	}
	return ""
}

func (x *CacheStorageConfiguration) GetS3() *CacheS3Configuration {
	if x != nil {
		return x.S3
	}
	return nil
}

type CacheS3Configuration struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Endpoint       string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Region         string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Bucket         string                 `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Prefix         string                 `protobuf:"bytes,4,opt,name=prefix,proto3" json:"prefix,omitempty"`
	ForcePathStyle bool                   `protobuf:"varint,5,opt,name=force_path_style,json=forcePathStyle,proto3" json:"force_path_style,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CacheS3Configuration) Reset() {
	*x = CacheS3Configuration{}
	mi := &file_component_v1_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheS3Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheS3Configuration) ProtoMessage() {}

func (x *CacheS3Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_component_v1_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheS3Configuration.ProtoReflect.Descriptor instead.
func (*CacheS3Configuration) Descriptor() ([]byte, []int) {
	return file_component_v1_service_proto_rawDescGZIP(), []int{18}
}

func (x *CacheS3Configuration) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *CacheS3Configuration) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CacheS3Configuration) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *CacheS3Configuration) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *CacheS3Configuration) GetForcePathStyle() bool {
	if x != nil {
		return x.ForcePathStyle
	}
	return false
}

type CacheUpstreamConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allow         []string               `protobuf:"bytes,1,rep,name=allow,proto3" json:"allow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheUpstreamConfiguration) Reset() {
	*x = CacheUpstreamConfiguration{}
	mi := &file_component_v1_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheUpstreamConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheUpstreamConfiguration) ProtoMessage() {}

func (x *CacheUpstreamConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_component_v1_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheUpstreamConfiguration.ProtoReflect.Descriptor instead.
func (*CacheUpstreamConfiguration) Descriptor() ([]byte, []int) {
	return file_component_v1_service_proto_rawDescGZIP(), []int{19}
}

func (x *CacheUpstreamConfiguration) GetAllow() []string {
	if x != nil {
		return x.Allow
	}
	return nil
}

type CacheStatus struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	PublicUrl                   string                 `protobuf:"bytes,1,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	ConfigRevision              int64                  `protobuf:"varint,2,opt,name=config_revision,json=configRevision,proto3" json:"config_revision,omitempty"`
	CacheBytes                  int64                  `protobuf:"varint,3,opt,name=cache_bytes,json=cacheBytes,proto3" json:"cache_bytes,omitempty"`
	MirrorBytes                 int64                  `protobuf:"varint,4,opt,name=mirror_bytes,json=mirrorBytes,proto3" json:"mirror_bytes,omitempty"`
	ScannedAtUnixMilliseconds   int64                  `protobuf:"varint,5,opt,name=scanned_at_unix_milliseconds,json=scannedAtUnixMilliseconds,proto3" json:"scanned_at_unix_milliseconds,omitempty"`
	LastCleanupUnixMilliseconds int64                  `protobuf:"varint,6,opt,name=last_cleanup_unix_milliseconds,json=lastCleanupUnixMilliseconds,proto3" json:"last_cleanup_unix_milliseconds,omitempty"`
	CleanupResult               string                 `protobuf:"bytes,7,opt,name=cleanup_result,json=cleanupResult,proto3" json:"cleanup_result,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *CacheStatus) Reset() {
	*x = CacheStatus{}
	mi := &file_component_v1_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheStatus) ProtoMessage() {}

func (x *CacheStatus) ProtoReflect() protoreflect.Message {
	mi := &file_component_v1_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheStatus.ProtoReflect.Descriptor instead.
func (*CacheStatus) Descriptor() ([]byte, []int) {
	return file_component_v1_service_proto_rawDescGZIP(), []int{20}
}

func (x *CacheStatus) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

func (x *CacheStatus) GetConfigRevision() int64 {
	if x != nil {
		return x.ConfigRevision
	}
	return 0
}

func (x *CacheStatus) GetCacheBytes() int64 {
	if x != nil {
		return x.CacheBytes
	}
	return 0
}

func (x *CacheStatus) GetMirrorBytes() int64 {
	if x != nil {
		return x.MirrorBytes
	}
	return 0
}

func (x *CacheStatus) GetScannedAtUnixMilliseconds() int64 {
	if x != nil {
		return x.ScannedAtUnixMilliseconds
	}
	return 0
}

func (x *CacheStatus) GetLastCleanupUnixMilliseconds() int64 {
	if x != nil {
		return x.LastCleanupUnixMilliseconds
	}
	return 0
}

func (x *CacheStatus) GetCleanupResult() string {
	if x != nil {
		return x.CleanupResult
	}
	return ""
}

type CacheGCGrant struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	CacheId                   string                 `protobuf:"bytes,1,opt,name=cache_id,json=cacheId,proto3" json:"cache_id,omitempty"`
	Id                        string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	ConfigRevision            int64                  `protobuf:"varint,3,opt,name=config_revision,json=configRevision,proto3" json:"config_revision,omitempty"`
	ExpiresAtUnixMilliseconds int64                  `protobuf:"varint,4,opt,name=expires_at_unix_milliseconds,json=expiresAtUnixMilliseconds,proto3" json:"expires_at_unix_milliseconds,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CacheGCGrant) Reset() {
	*x = CacheGCGrant{}
	mi := &file_component_v1_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheGCGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheGCGrant) ProtoMessage() {}

func (x *CacheGCGrant) ProtoReflect() protoreflect.Message {
	mi := &file_component_v1_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheGCGrant.ProtoReflect.Descriptor instead.
func (*CacheGCGrant) Descriptor() ([]byte, []int) {
	return file_component_v1_service_proto_rawDescGZIP(), []int{21}
}

func (x *CacheGCGrant) GetCacheId() string {
	if x != nil {
		return x.CacheId
	}
	return ""
}

func (x *CacheGCGrant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CacheGCGrant) GetConfigRevision() int64 {
	if x != nil {
		return x.ConfigRevision
	}
	return 0
}

func (x *CacheGCGrant) GetExpiresAtUnixMilliseconds() int64 {
	if x != nil {
		return x.ExpiresAtUnixMilliseconds
	}
	return 0
}

type CacheGCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheGCRequest) Reset() {
	*x = CacheGCRequest{}
	mi := &file_component_v1_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheGCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheGCRequest) ProtoMessage() {}

func (x *CacheGCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_component_v1_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheGCRequest.ProtoReflect.Descriptor instead.
func (*CacheGCRequest) Descriptor() ([]byte, []int) {
	return file_component_v1_service_proto_rawDescGZIP(), []int{22}
}

type CacheGCComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrantId       string                 `protobuf:"bytes,1,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheGCComplete) Reset() {
	*x = CacheGCComplete{}
	mi := &file_component_v1_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheGCComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheGCComplete) ProtoMessage() {}

func (x *CacheGCComplete) ProtoReflect() protoreflect.Message {
	mi := &file_component_v1_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheGCComplete.ProtoReflect.Descriptor instead.
func (*CacheGCComplete) Descriptor() ([]byte, []int) {
	return file_component_v1_service_proto_rawDescGZIP(), []int{23}
}

func (x *CacheGCComplete) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

var File_component_v1_service_proto protoreflect.FileDescriptor

const file_component_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1acomponent/v1/service.proto\x12\fcomponent.v1\x1a\x16agent/v1/service.proto\"\xa2\x02\n" +
	"\x15GatewayControlRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12`\n" +
	"\x0factive_sessions\x18\x04 \x03(\v27.component.v1.GatewayControlRequest.ActiveSessionsEntryR\x0eactiveSessions\x1aA\n" +
	"\x13ActiveSessionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xd9\x02\n" +
	"\x16GatewayControlResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12A\n" +
	"\x1dpermit_valid_for_milliseconds\x18\x03 \x01(\x03R\x1apermitValidForMilliseconds\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\x12\x1a\n" +
	"\bsnapshot\x18\x05 \x01(\bR\bsnapshot\x12B\n" +
	"\x06config\x18\x06 \x01(\v2*.component.v1.GatewayConfigurationSnapshotR\x06config\x12=\n" +
	"\bruntimes\x18\a \x03(\v2!.component.v1.GatewayRuntimeRouteR\bruntimes\"\x8c\x05\n" +
	"\x1cGatewayConfigurationSnapshot\x12\x1f\n" +
	"\vhttp_listen\x18\x01 \x01(\tR\n" +
	"httpListen\x12\x1d\n" +
	"\n" +
	"public_url\x18\x02 \x01(\tR\tpublicUrl\x12\x1d\n" +
	"\n" +
	"ssh_listen\x18\x03 \x01(\tR\tsshListen\x12,\n" +
	"\x12ssh_public_address\x18\x04 \x01(\tR\x10sshPublicAddress\x128\n" +
	"\x18session_ttl_milliseconds\x18\x05 \x01(\x03R\x16sessionTtlMilliseconds\x12I\n" +
	"!session_idle_timeout_milliseconds\x18\x06 \x01(\x03R\x1esessionIdleTimeoutMilliseconds\x12H\n" +
	" revalidate_interval_milliseconds\x18\a \x01(\x03R\x1erevalidateIntervalMilliseconds\x12;\n" +
	"\x1amax_sessions_per_codespace\x18\b \x01(\x05R\x17maxSessionsPerCodespace\x121\n" +
	"\x15max_sessions_per_user\x18\t \x01(\x05R\x12maxSessionsPerUser\x12!\n" +
	"\fmax_inflight\x18\n" +
	" \x01(\x05R\vmaxInflight\x127\n" +
	"\x18max_inflight_per_session\x18\v \x01(\x05R\x15maxInflightPerSession\x12D\n" +
	"\x1fmax_channels_per_ssh_connection\x18\f \x01(\x05R\x1bmaxChannelsPerSshConnection\"\xbc\x02\n" +
	"\x13GatewayRuntimeRoute\x12\x19\n" +
	"\bsite_uid\x18\x01 \x01(\tR\asiteUid\x12!\n" +
	"\fresource_uid\x18\x02 \x01(\tR\vresourceUid\x12!\n" +
	"\fruntime_uuid\x18\x03 \x01(\tR\vruntimeUuid\x12\x17\n" +
	"\apod_uid\x18\x04 \x01(\tR\x06podUid\x12#\n" +
	"\ragent_address\x18\x05 \x01(\tR\fagentAddress\x12%\n" +
	"\x0etarget_version\x18\x06 \x01(\x03R\rtargetVersion\x12;\n" +
	"\tendpoints\x18\a \x03(\v2\x1d.component.v1.GatewayEndpointR\tendpoints\x12\"\n" +
	"\rgitea_web_url\x18\b \x01(\tR\vgiteaWebUrl\"`\n" +
	"\x0fGatewayEndpoint\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x16\n" +
	"\x06public\x18\x03 \x01(\bR\x06public\"\xdd\x03\n" +
	"\x17AuthorizeGatewayRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12B\n" +
	"\topen_code\x18\x02 \x01(\v2#.component.v1.OpenCodeAuthorizationH\x00R\bopenCode\x12T\n" +
	"\x0fpublic_endpoint\x18\x03 \x01(\v2).component.v1.PublicEndpointAuthorizationH\x00R\x0epublicEndpoint\x12O\n" +
	"\x0essh_public_key\x18\x04 \x01(\v2'.component.v1.SSHPublicKeyAuthorizationH\x00R\fsshPublicKey\x12W\n" +
	"\x10endpoint_session\x18\x05 \x01(\v2*.component.v1.EndpointSessionAuthorizationH\x00R\x0fendpointSession\x12H\n" +
	"\vssh_session\x18\x06 \x01(\v2%.component.v1.SSHSessionAuthorizationH\x00R\n" +
	"sshSessionB\t\n" +
	"\arequest\"o\n" +
	"\x15OpenCodeAuthorization\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12!\n" +
	"\fruntime_uuid\x18\x02 \x01(\tR\vruntimeUuid\x12\x1f\n" +
	"\vendpoint_id\x18\x03 \x01(\tR\n" +
	"endpointId\"a\n" +
	"\x1bPublicEndpointAuthorization\x12!\n" +
	"\fruntime_uuid\x18\x01 \x01(\tR\vruntimeUuid\x12\x1f\n" +
	"\vendpoint_id\x18\x02 \x01(\tR\n" +
	"endpointId\"]\n" +
	"\x19SSHPublicKeyAuthorization\x12!\n" +
	"\fruntime_uuid\x18\x01 \x01(\tR\vruntimeUuid\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\"{\n" +
	"\x1cEndpointSessionAuthorization\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\fruntime_uuid\x18\x02 \x01(\tR\vruntimeUuid\x12\x1f\n" +
	"\vendpoint_id\x18\x03 \x01(\tR\n" +
	"endpointId\"U\n" +
	"\x17SSHSessionAuthorization\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\fruntime_uuid\x18\x02 \x01(\tR\vruntimeUuid\"\xba\x01\n" +
	"\x18AuthorizeGatewayResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12'\n" +
	"\x0fdenied_category\x18\x02 \x01(\tR\x0edeniedCategory\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12!\n" +
	"\fruntime_uuid\x18\x04 \x01(\tR\vruntimeUuid\x12\x1f\n" +
	"\vendpoint_id\x18\x05 \x01(\tR\n" +
	"endpointId\"\xc4\x01\n" +
	"\x17IssueAgentAccessRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12!\n" +
	"\fruntime_uuid\x18\x02 \x01(\tR\vruntimeUuid\x12:\n" +
	"\n" +
	"capability\x18\x03 \x01(\x0e2\x1a.agent.v1.AccessCapabilityR\n" +
	"capability\x12\x1f\n" +
	"\vendpoint_id\x18\x04 \x01(\tR\n" +
	"endpointId\"o\n" +
	"\x18IssueAgentAccessResponse\x12;\n" +
	"\aruntime\x18\x01 \x01(\v2!.component.v1.GatewayRuntimeRouteR\aruntime\x12\x16\n" +
	"\x06ticket\x18\x02 \x01(\tR\x06ticket\"\xd5\x02\n" +
	"\x13CacheControlRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x19\n" +
	"\bcache_id\x18\x02 \x01(\tR\acacheId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequence\x121\n" +
	"\x06status\x18\x05 \x01(\v2\x19.component.v1.CacheStatusR\x06status\x129\n" +
	"\bbegin_gc\x18\x06 \x01(\v2\x1c.component.v1.CacheGCRequestH\x00R\abeginGc\x12@\n" +
	"\vcomplete_gc\x18\a \x01(\v2\x1d.component.v1.CacheGCCompleteH\x00R\n" +
	"completeGcB\r\n" +
	"\vmaintenance\"\x91\x02\n" +
	"\x14CacheControlResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12A\n" +
	"\x1dpermit_valid_for_milliseconds\x18\x03 \x01(\x03R\x1apermitValidForMilliseconds\x128\n" +
	"\x06config\x18\x04 \x01(\v2 .component.v1.CacheConfigurationR\x06config\x125\n" +
	"\bgc_grant\x18\x05 \x01(\v2\x1a.component.v1.CacheGCGrantR\agcGrant\"\xa6\x04\n" +
	"\x12CacheConfiguration\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x03R\brevision\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x16\n" +
	"\x06listen\x18\x05 \x01(\tR\x06listen\x12\x1d\n" +
	"\n" +
	"public_url\x18\x06 \x01(\tR\tpublicUrl\x12A\n" +
	"\astorage\x18\a \x01(\v2'.component.v1.CacheStorageConfigurationR\astorage\x12\x19\n" +
	"\bmax_size\x18\b \x01(\tR\amaxSize\x120\n" +
	"\x14max_age_milliseconds\x18\t \x01(\x03R\x12maxAgeMilliseconds\x128\n" +
	"\x18gc_interval_milliseconds\x18\n" +
	" \x01(\x03R\x16gcIntervalMilliseconds\x12M\n" +
	"\tupstreams\x18\v \x03(\v2/.component.v1.CacheConfiguration.UpstreamsEntryR\tupstreams\x1af\n" +
	"\x0eUpstreamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12>\n" +
	"\x05value\x18\x02 \x01(\v2(.component.v1.CacheUpstreamConfigurationR\x05value:\x028\x01\"\xa1\x01\n" +
	"\x19CacheStorageConfiguration\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12$\n" +
	"\x0emin_free_space\x18\x03 \x01(\tR\fminFreeSpace\x122\n" +
	"\x02s3\x18\x04 \x01(\v2\".component.v1.CacheS3ConfigurationR\x02s3\"\xa4\x01\n" +
	"\x14CacheS3Configuration\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x16\n" +
	"\x06bucket\x18\x03 \x01(\tR\x06bucket\x12\x16\n" +
	"\x06prefix\x18\x04 \x01(\tR\x06prefix\x12(\n" +
	"\x10force_path_style\x18\x05 \x01(\bR\x0eforcePathStyle\"2\n" +
	"\x1aCacheUpstreamConfiguration\x12\x14\n" +
	"\x05allow\x18\x01 \x03(\tR\x05allow\"\xc6\x02\n" +
	"\vCacheStatus\x12\x1d\n" +
	"\n" +
	"public_url\x18\x01 \x01(\tR\tpublicUrl\x12'\n" +
	"\x0fconfig_revision\x18\x02 \x01(\x03R\x0econfigRevision\x12\x1f\n" +
	"\vcache_bytes\x18\x03 \x01(\x03R\n" +
	"cacheBytes\x12!\n" +
	"\fmirror_bytes\x18\x04 \x01(\x03R\vmirrorBytes\x12?\n" +
	"\x1cscanned_at_unix_milliseconds\x18\x05 \x01(\x03R\x19scannedAtUnixMilliseconds\x12C\n" +
	"\x1elast_cleanup_unix_milliseconds\x18\x06 \x01(\x03R\x1blastCleanupUnixMilliseconds\x12%\n" +
	"\x0ecleanup_result\x18\a \x01(\tR\rcleanupResult\"\xa3\x01\n" +
	"\fCacheGCGrant\x12\x19\n" +
	"\bcache_id\x18\x01 \x01(\tR\acacheId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12'\n" +
	"\x0fconfig_revision\x18\x03 \x01(\x03R\x0econfigRevision\x12?\n" +
	"\x1cexpires_at_unix_milliseconds\x18\x04 \x01(\x03R\x19expiresAtUnixMilliseconds\"\x10\n" +
	"\x0eCacheGCRequest\",\n" +
	"\x0fCacheGCComplete\x12\x19\n" +
	"\bgrant_id\x18\x01 \x01(\tR\agrantId2\x94\x03\n" +
	"\x10ComponentService\x12_\n" +
	"\x0eGatewayControl\x12#.component.v1.GatewayControlRequest\x1a$.component.v1.GatewayControlResponse(\x010\x01\x12a\n" +
	"\x10AuthorizeGateway\x12%.component.v1.AuthorizeGatewayRequest\x1a&.component.v1.AuthorizeGatewayResponse\x12a\n" +
	"\x10IssueAgentAccess\x12%.component.v1.IssueAgentAccessRequest\x1a&.component.v1.IssueAgentAccessResponse\x12Y\n" +
	"\fCacheControl\x12!.component.v1.CacheControlRequest\x1a\".component.v1.CacheControlResponse(\x010\x01B;Z9gitea.dev/codespace/internal/rpc/component/v1;componentv1b\x06proto3"

var (
	file_component_v1_service_proto_rawDescOnce sync.Once
	file_component_v1_service_proto_rawDescData []byte
)

func file_component_v1_service_proto_rawDescGZIP() []byte {
	file_component_v1_service_proto_rawDescOnce.Do(func() {
		file_component_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_component_v1_service_proto_rawDesc), len(file_component_v1_service_proto_rawDesc)))
	})
	return file_component_v1_service_proto_rawDescData
}

var file_component_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_component_v1_service_proto_goTypes = []any{
	(*GatewayControlRequest)(nil),        // 0: component.v1.GatewayControlRequest
	(*GatewayControlResponse)(nil),       // 1: component.v1.GatewayControlResponse
	(*GatewayConfigurationSnapshot)(nil), // 2: component.v1.GatewayConfigurationSnapshot
	(*GatewayRuntimeRoute)(nil),          // 3: component.v1.GatewayRuntimeRoute
	(*GatewayEndpoint)(nil),              // 4: component.v1.GatewayEndpoint
	(*AuthorizeGatewayRequest)(nil),      // 5: component.v1.AuthorizeGatewayRequest
	(*OpenCodeAuthorization)(nil),        // 6: component.v1.OpenCodeAuthorization
	(*PublicEndpointAuthorization)(nil),  // 7: component.v1.PublicEndpointAuthorization
	(*SSHPublicKeyAuthorization)(nil),    // 8: component.v1.SSHPublicKeyAuthorization
	(*EndpointSessionAuthorization)(nil), // 9: component.v1.EndpointSessionAuthorization
	(*SSHSessionAuthorization)(nil),      // 10: component.v1.SSHSessionAuthorization
	(*AuthorizeGatewayResponse)(nil),     // 11: component.v1.AuthorizeGatewayResponse
	(*IssueAgentAccessRequest)(nil),      // 12: component.v1.IssueAgentAccessRequest
	(*IssueAgentAccessResponse)(nil),     // 13: component.v1.IssueAgentAccessResponse
	(*CacheControlRequest)(nil),          // 14: component.v1.CacheControlRequest
	(*CacheControlResponse)(nil),         // 15: component.v1.CacheControlResponse
	(*CacheConfiguration)(nil),           // 16: component.v1.CacheConfiguration
	(*CacheStorageConfiguration)(nil),    // 17: component.v1.CacheStorageConfiguration
	(*CacheS3Configuration)(nil),         // 18: component.v1.CacheS3Configuration
	(*CacheUpstreamConfiguration)(nil),   // 19: component.v1.CacheUpstreamConfiguration
	(*CacheStatus)(nil),                  // 20: component.v1.CacheStatus
	(*CacheGCGrant)(nil),                 // 21: component.v1.CacheGCGrant
	(*CacheGCRequest)(nil),               // 22: component.v1.CacheGCRequest
	(*CacheGCComplete)(nil),              // 23: component.v1.CacheGCComplete
	nil,                                  // 24: component.v1.GatewayControlRequest.ActiveSessionsEntry
	nil,                                  // 25: component.v1.CacheConfiguration.UpstreamsEntry
	(v1.AccessCapability)(0),             // 26: agent.v1.AccessCapability
}
var file_component_v1_service_proto_depIdxs = []int32{
	24, // 0: component.v1.GatewayControlRequest.active_sessions:type_name -> component.v1.GatewayControlRequest.ActiveSessionsEntry
	2,  // 1: component.v1.GatewayControlResponse.config:type_name -> component.v1.GatewayConfigurationSnapshot
	3,  // 2: component.v1.GatewayControlResponse.runtimes:type_name -> component.v1.GatewayRuntimeRoute
	4,  // 3: component.v1.GatewayRuntimeRoute.endpoints:type_name -> component.v1.GatewayEndpoint
	6,  // 4: component.v1.AuthorizeGatewayRequest.open_code:type_name -> component.v1.OpenCodeAuthorization
	7,  // 5: component.v1.AuthorizeGatewayRequest.public_endpoint:type_name -> component.v1.PublicEndpointAuthorization
	8,  // 6: component.v1.AuthorizeGatewayRequest.ssh_public_key:type_name -> component.v1.SSHPublicKeyAuthorization
	9,  // 7: component.v1.AuthorizeGatewayRequest.endpoint_session:type_name -> component.v1.EndpointSessionAuthorization
	10, // 8: component.v1.AuthorizeGatewayRequest.ssh_session:type_name -> component.v1.SSHSessionAuthorization
	26, // 9: component.v1.IssueAgentAccessRequest.capability:type_name -> agent.v1.AccessCapability
	3,  // 10: component.v1.IssueAgentAccessResponse.runtime:type_name -> component.v1.GatewayRuntimeRoute
	20, // 11: component.v1.CacheControlRequest.status:type_name -> component.v1.CacheStatus
	22, // 12: component.v1.CacheControlRequest.begin_gc:type_name -> component.v1.CacheGCRequest
	23, // 13: component.v1.CacheControlRequest.complete_gc:type_name -> component.v1.CacheGCComplete
	16, // 14: component.v1.CacheControlResponse.config:type_name -> component.v1.CacheConfiguration
	21, // 15: component.v1.CacheControlResponse.gc_grant:type_name -> component.v1.CacheGCGrant
	17, // 16: component.v1.CacheConfiguration.storage:type_name -> component.v1.CacheStorageConfiguration
	25, // 17: component.v1.CacheConfiguration.upstreams:type_name -> component.v1.CacheConfiguration.UpstreamsEntry
	18, // 18: component.v1.CacheStorageConfiguration.s3:type_name -> component.v1.CacheS3Configuration
	19, // 19: component.v1.CacheConfiguration.UpstreamsEntry.value:type_name -> component.v1.CacheUpstreamConfiguration
	0,  // 20: component.v1.ComponentService.GatewayControl:input_type -> component.v1.GatewayControlRequest
	5,  // 21: component.v1.ComponentService.AuthorizeGateway:input_type -> component.v1.AuthorizeGatewayRequest
	12, // 22: component.v1.ComponentService.IssueAgentAccess:input_type -> component.v1.IssueAgentAccessRequest
	14, // 23: component.v1.ComponentService.CacheControl:input_type -> component.v1.CacheControlRequest
	1,  // 24: component.v1.ComponentService.GatewayControl:output_type -> component.v1.GatewayControlResponse
	11, // 25: component.v1.ComponentService.AuthorizeGateway:output_type -> component.v1.AuthorizeGatewayResponse
	13, // 26: component.v1.ComponentService.IssueAgentAccess:output_type -> component.v1.IssueAgentAccessResponse
	15, // 27: component.v1.ComponentService.CacheControl:output_type -> component.v1.CacheControlResponse
	24, // [24:28] is the sub-list for method output_type
	20, // [20:24] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_component_v1_service_proto_init() }
func file_component_v1_service_proto_init() {
	if File_component_v1_service_proto != nil {
		return
	}
	file_component_v1_service_proto_msgTypes[5].OneofWrappers = []any{
		(*AuthorizeGatewayRequest_OpenCode)(nil),
		(*AuthorizeGatewayRequest_PublicEndpoint)(nil),
		(*AuthorizeGatewayRequest_SshPublicKey)(nil),
		(*AuthorizeGatewayRequest_EndpointSession)(nil),
		(*AuthorizeGatewayRequest_SshSession)(nil),
	}
	file_component_v1_service_proto_msgTypes[14].OneofWrappers = []any{
		(*CacheControlRequest_BeginGc)(nil),
		(*CacheControlRequest_CompleteGc)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_component_v1_service_proto_rawDesc), len(file_component_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_component_v1_service_proto_goTypes,
		DependencyIndexes: file_component_v1_service_proto_depIdxs,
		MessageInfos:      file_component_v1_service_proto_msgTypes,
	}.Build()
	File_component_v1_service_proto = out.File
	file_component_v1_service_proto_goTypes = nil
	file_component_v1_service_proto_depIdxs = nil
}
