// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agent/v1/service.proto

package agentv1

import (
	v1 "gitea.dev/codespace-proto-go/codespace/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AccessCapability identifies the single operation authorized by a ticket.
type AccessCapability int32

const (
	AccessCapability_ACCESS_CAPABILITY_UNSPECIFIED  AccessCapability = 0
	AccessCapability_ACCESS_CAPABILITY_TERMINAL     AccessCapability = 1
	AccessCapability_ACCESS_CAPABILITY_COMMAND      AccessCapability = 2
	AccessCapability_ACCESS_CAPABILITY_SFTP         AccessCapability = 3
	AccessCapability_ACCESS_CAPABILITY_ENDPOINT     AccessCapability = 4
	AccessCapability_ACCESS_CAPABILITY_LOOPBACK_TCP AccessCapability = 5
)

// Enum value maps for AccessCapability.
var (
	AccessCapability_name = map[int32]string{
		0: "ACCESS_CAPABILITY_UNSPECIFIED",
		1: "ACCESS_CAPABILITY_TERMINAL",
		2: "ACCESS_CAPABILITY_COMMAND",
		3: "ACCESS_CAPABILITY_SFTP",
		4: "ACCESS_CAPABILITY_ENDPOINT",
		5: "ACCESS_CAPABILITY_LOOPBACK_TCP",
	}
	AccessCapability_value = map[string]int32{
		"ACCESS_CAPABILITY_UNSPECIFIED":  0,
		"ACCESS_CAPABILITY_TERMINAL":     1,
		"ACCESS_CAPABILITY_COMMAND":      2,
		"ACCESS_CAPABILITY_SFTP":         3,
		"ACCESS_CAPABILITY_ENDPOINT":     4,
		"ACCESS_CAPABILITY_LOOPBACK_TCP": 5,
	}
)

func (x AccessCapability) Enum() *AccessCapability {
	p := new(AccessCapability)
	*p = x
	return p
}

func (x AccessCapability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessCapability) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_v1_service_proto_enumTypes[0].Descriptor()
}

func (AccessCapability) Type() protoreflect.EnumType {
	return &file_agent_v1_service_proto_enumTypes[0]
}

func (x AccessCapability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessCapability.Descriptor instead.
func (AccessCapability) EnumDescriptor() ([]byte, []int) {
	return file_agent_v1_service_proto_rawDescGZIP(), []int{0}
}

type RuntimeEndpointServiceListRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RuntimeEndpointServiceListRequest) Reset() {
	*x = RuntimeEndpointServiceListRequest{}
	mi := &file_agent_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeEndpointServiceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeEndpointServiceListRequest) ProtoMessage() {}

func (x *RuntimeEndpointServiceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeEndpointServiceListRequest.ProtoReflect.Descriptor instead.
func (*RuntimeEndpointServiceListRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *RuntimeEndpointServiceListRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

type RuntimeEndpointServiceListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []*v1.RuntimeEndpoint  `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeEndpointServiceListResponse) Reset() {
	*x = RuntimeEndpointServiceListResponse{}
	mi := &file_agent_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeEndpointServiceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeEndpointServiceListResponse) ProtoMessage() {}

func (x *RuntimeEndpointServiceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeEndpointServiceListResponse.ProtoReflect.Descriptor instead.
func (*RuntimeEndpointServiceListResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *RuntimeEndpointServiceListResponse) GetEndpoints() []*v1.RuntimeEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type RuntimeEndpointServiceSetRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Endpoint        *v1.RuntimeEndpoint    `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RuntimeEndpointServiceSetRequest) Reset() {
	*x = RuntimeEndpointServiceSetRequest{}
	mi := &file_agent_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeEndpointServiceSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeEndpointServiceSetRequest) ProtoMessage() {}

func (x *RuntimeEndpointServiceSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeEndpointServiceSetRequest.ProtoReflect.Descriptor instead.
func (*RuntimeEndpointServiceSetRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *RuntimeEndpointServiceSetRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *RuntimeEndpointServiceSetRequest) GetEndpoint() *v1.RuntimeEndpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

type RuntimeEndpointServiceSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeEndpointServiceSetResponse) Reset() {
	*x = RuntimeEndpointServiceSetResponse{}
	mi := &file_agent_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeEndpointServiceSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeEndpointServiceSetResponse) ProtoMessage() {}

func (x *RuntimeEndpointServiceSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeEndpointServiceSetResponse.ProtoReflect.Descriptor instead.
func (*RuntimeEndpointServiceSetResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_service_proto_rawDescGZIP(), []int{3}
}

type RuntimeEndpointServiceDeleteRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	EndpointId      string                 `protobuf:"bytes,2,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RuntimeEndpointServiceDeleteRequest) Reset() {
	*x = RuntimeEndpointServiceDeleteRequest{}
	mi := &file_agent_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeEndpointServiceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeEndpointServiceDeleteRequest) ProtoMessage() {}

func (x *RuntimeEndpointServiceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeEndpointServiceDeleteRequest.ProtoReflect.Descriptor instead.
func (*RuntimeEndpointServiceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *RuntimeEndpointServiceDeleteRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *RuntimeEndpointServiceDeleteRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

type RuntimeEndpointServiceDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeEndpointServiceDeleteResponse) Reset() {
	*x = RuntimeEndpointServiceDeleteResponse{}
	mi := &file_agent_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeEndpointServiceDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeEndpointServiceDeleteResponse) ProtoMessage() {}

func (x *RuntimeEndpointServiceDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeEndpointServiceDeleteResponse.ProtoReflect.Descriptor instead.
func (*RuntimeEndpointServiceDeleteResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_service_proto_rawDescGZIP(), []int{5}
}

type ControlRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Fresh per connection; stale session replies cannot renew execution.
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Strictly increasing within this control session.
	Sequence uint64       `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Report   *AgentReport `protobuf:"bytes,4,opt,name=report,proto3" json:"report,omitempty"`
	// accepted_operation_rversion is the operation payload retained by this Agent process.
	AcceptedOperationRversion int64 `protobuf:"varint,5,opt,name=accepted_operation_rversion,json=acceptedOperationRversion,proto3" json:"accepted_operation_rversion,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ControlRequest) Reset() {
	*x = ControlRequest{}
	mi := &file_agent_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRequest) ProtoMessage() {}

func (x *ControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlRequest.ProtoReflect.Descriptor instead.
func (*ControlRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *ControlRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ControlRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ControlRequest) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ControlRequest) GetReport() *AgentReport {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *ControlRequest) GetAcceptedOperationRversion() int64 {
	if x != nil {
		return x.AcceptedOperationRversion
	}
	return 0
}

type AgentReport struct {
	state             protoimpl.MessageState   `protogen:"open.v1"`
	OperationRversion int64                    `protobuf:"varint,1,opt,name=operation_rversion,json=operationRversion,proto3" json:"operation_rversion,omitempty"`
	GitSshPublicKey   []byte                   `protobuf:"bytes,2,opt,name=git_ssh_public_key,json=gitSshPublicKey,proto3" json:"git_ssh_public_key,omitempty"`
	Result            *OperationResult         `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Target            *AccessTarget            `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Boot              *v1.RuntimeBoot          `protobuf:"bytes,5,opt,name=boot,proto3" json:"boot,omitempty"`
	ResourceUsage     *v1.RuntimeResourceUsage `protobuf:"bytes,6,opt,name=resource_usage,json=resourceUsage,proto3" json:"resource_usage,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AgentReport) Reset() {
	*x = AgentReport{}
	mi := &file_agent_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentReport) ProtoMessage() {}

func (x *AgentReport) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentReport.ProtoReflect.Descriptor instead.
func (*AgentReport) Descriptor() ([]byte, []int) {
	return file_agent_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *AgentReport) GetOperationRversion() int64 {
	if x != nil {
		return x.OperationRversion
	}
	return 0
}

func (x *AgentReport) GetGitSshPublicKey() []byte {
	if x != nil {
		return x.GitSshPublicKey
	}
	return nil
}

func (x *AgentReport) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *AgentReport) GetTarget() *AccessTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *AgentReport) GetBoot() *v1.RuntimeBoot {
	if x != nil {
		return x.Boot
	}
	return nil
}

func (x *AgentReport) GetResourceUsage() *v1.RuntimeResourceUsage {
	if x != nil {
		return x.ResourceUsage
	}
	return nil
}

type OperationResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OperationRversion int64                  `protobuf:"varint,1,opt,name=operation_rversion,json=operationRversion,proto3" json:"operation_rversion,omitempty"`
	Status            v1.FinalStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=codespace.v1.FinalStatus" json:"status,omitempty"`
	Message           string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OperationResult) Reset() {
	*x = OperationResult{}
	mi := &file_agent_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResult) ProtoMessage() {}

func (x *OperationResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResult.ProtoReflect.Descriptor instead.
func (*OperationResult) Descriptor() ([]byte, []int) {
	return file_agent_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *OperationResult) GetOperationRversion() int64 {
	if x != nil {
		return x.OperationRversion
	}
	return 0
}

func (x *OperationResult) GetStatus() v1.FinalStatus {
	if x != nil {
		return x.Status
	}
	return v1.FinalStatus(0)
}

func (x *OperationResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ControlResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Sequence  uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Measured from the caller's request send time, not reply receipt time.
	PermitValidForMilliseconds int64                   `protobuf:"varint,3,opt,name=permit_valid_for_milliseconds,json=permitValidForMilliseconds,proto3" json:"permit_valid_for_milliseconds,omitempty"`
	Operation                  *v1.OperationPayload    `protobuf:"bytes,4,opt,name=operation,proto3" json:"operation,omitempty"`
	Access                     *v1.RuntimeAccessBundle `protobuf:"bytes,5,opt,name=access,proto3" json:"access,omitempty"`
	// A durable Manager result permits Agent to retire this pending result.
	AcknowledgedResultVersion int64 `protobuf:"varint,6,opt,name=acknowledged_result_version,json=acknowledgedResultVersion,proto3" json:"acknowledged_result_version,omitempty"`
	CancelExecution           bool  `protobuf:"varint,7,opt,name=cancel_execution,json=cancelExecution,proto3" json:"cancel_execution,omitempty"`
	// Pinned platform options, applied before the Docker daemon starts.
	Runtime *RuntimeOptions `protobuf:"bytes,8,opt,name=runtime,proto3" json:"runtime,omitempty"`
	// Ed25519 verification key for Manager-issued, limited access tickets.
	AccessVerificationKey []byte `protobuf:"bytes,9,opt,name=access_verification_key,json=accessVerificationKey,proto3" json:"access_verification_key,omitempty"`
	// operation_rversion identifies the operation covered by this execution permit.
	OperationRversion int64 `protobuf:"varint,10,opt,name=operation_rversion,json=operationRversion,proto3" json:"operation_rversion,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ControlResponse) Reset() {
	*x = ControlResponse{}
	mi := &file_agent_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlResponse) ProtoMessage() {}

func (x *ControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlResponse.ProtoReflect.Descriptor instead.
func (*ControlResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *ControlResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ControlResponse) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ControlResponse) GetPermitValidForMilliseconds() int64 {
	if x != nil {
		return x.PermitValidForMilliseconds
	}
	return 0
}

func (x *ControlResponse) GetOperation() *v1.OperationPayload {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *ControlResponse) GetAccess() *v1.RuntimeAccessBundle {
	if x != nil {
		return x.Access
	}
	return nil
}

func (x *ControlResponse) GetAcknowledgedResultVersion() int64 {
	if x != nil {
		return x.AcknowledgedResultVersion
	}
	return 0
}

func (x *ControlResponse) GetCancelExecution() bool {
	if x != nil {
		return x.CancelExecution
	}
	return false
}

func (x *ControlResponse) GetRuntime() *RuntimeOptions {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *ControlResponse) GetAccessVerificationKey() []byte {
	if x != nil {
		return x.AccessVerificationKey
	}
	return nil
}

func (x *ControlResponse) GetOperationRversion() int64 {
	if x != nil {
		return x.OperationRversion
	}
	return 0
}

type RuntimeOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GitSshKeyType string                 `protobuf:"bytes,1,opt,name=git_ssh_key_type,json=gitSshKeyType,proto3" json:"git_ssh_key_type,omitempty"`
	// cache contains one Manager-authorized registry endpoint for this runtime.
	Cache         *RuntimeCache `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeOptions) Reset() {
	*x = RuntimeOptions{}
	mi := &file_agent_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeOptions) ProtoMessage() {}

func (x *RuntimeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeOptions.ProtoReflect.Descriptor instead.
func (*RuntimeOptions) Descriptor() ([]byte, []int) {
	return file_agent_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *RuntimeOptions) GetGitSshKeyType() string {
	if x != nil {
		return x.GitSshKeyType
	}
	return ""
}

func (x *RuntimeOptions) GetCache() *RuntimeCache {
	if x != nil {
		return x.Cache
	}
	return nil
}

type RuntimeCache struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	BuildRegistry string                         `protobuf:"bytes,1,opt,name=build_registry,json=buildRegistry,proto3" json:"build_registry,omitempty"`
	BuildScope    string                         `protobuf:"bytes,2,opt,name=build_scope,json=buildScope,proto3" json:"build_scope,omitempty"`
	Mirrors       map[string]string              `protobuf:"bytes,3,rep,name=mirrors,proto3" json:"mirrors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Credentials   map[string]*RegistryCredential `protobuf:"bytes,4,rep,name=credentials,proto3" json:"credentials,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeCache) Reset() {
	*x = RuntimeCache{}
	mi := &file_agent_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeCache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeCache) ProtoMessage() {}

func (x *RuntimeCache) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeCache.ProtoReflect.Descriptor instead.
func (*RuntimeCache) Descriptor() ([]byte, []int) {
	return file_agent_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *RuntimeCache) GetBuildRegistry() string {
	if x != nil {
		return x.BuildRegistry
	}
	return ""
}

func (x *RuntimeCache) GetBuildScope() string {
	if x != nil {
		return x.BuildScope
	}
	return ""
}

func (x *RuntimeCache) GetMirrors() map[string]string {
	if x != nil {
		return x.Mirrors
	}
	return nil
}

func (x *RuntimeCache) GetCredentials() map[string]*RegistryCredential {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type RegistryCredential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryCredential) Reset() {
	*x = RegistryCredential{}
	mi := &file_agent_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryCredential) ProtoMessage() {}

func (x *RegistryCredential) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryCredential.ProtoReflect.Descriptor instead.
func (*RegistryCredential) Descriptor() ([]byte, []int) {
	return file_agent_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *RegistryCredential) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegistryCredential) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AccessTarget struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Version            int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	PrimaryContainerId string                 `protobuf:"bytes,2,opt,name=primary_container_id,json=primaryContainerId,proto3" json:"primary_container_id,omitempty"`
	Endpoints          []*EndpointTarget      `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Ready              bool                   `protobuf:"varint,4,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AccessTarget) Reset() {
	*x = AccessTarget{}
	mi := &file_agent_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessTarget) ProtoMessage() {}

func (x *AccessTarget) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessTarget.ProtoReflect.Descriptor instead.
func (*AccessTarget) Descriptor() ([]byte, []int) {
	return file_agent_v1_service_proto_rawDescGZIP(), []int{13}
}

func (x *AccessTarget) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AccessTarget) GetPrimaryContainerId() string {
	if x != nil {
		return x.PrimaryContainerId
	}
	return ""
}

func (x *AccessTarget) GetEndpoints() []*EndpointTarget {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *AccessTarget) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type EndpointTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      *v1.RuntimeEndpoint    `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointTarget) Reset() {
	*x = EndpointTarget{}
	mi := &file_agent_v1_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointTarget) ProtoMessage() {}

func (x *EndpointTarget) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointTarget.ProtoReflect.Descriptor instead.
func (*EndpointTarget) Descriptor() ([]byte, []int) {
	return file_agent_v1_service_proto_rawDescGZIP(), []int{14}
}

func (x *EndpointTarget) GetEndpoint() *v1.RuntimeEndpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *EndpointTarget) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *EndpointTarget) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type UploadLogsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion   uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	OperationRversion int64                  `protobuf:"varint,2,opt,name=operation_rversion,json=operationRversion,proto3" json:"operation_rversion,omitempty"`
	Offset            int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Lines             []*v1.LogLine          `protobuf:"bytes,4,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UploadLogsRequest) Reset() {
	*x = UploadLogsRequest{}
	mi := &file_agent_v1_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadLogsRequest) ProtoMessage() {}

func (x *UploadLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadLogsRequest.ProtoReflect.Descriptor instead.
func (*UploadLogsRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_service_proto_rawDescGZIP(), []int{15}
}

func (x *UploadLogsRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *UploadLogsRequest) GetOperationRversion() int64 {
	if x != nil {
		return x.OperationRversion
	}
	return 0
}

func (x *UploadLogsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *UploadLogsRequest) GetLines() []*v1.LogLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

type UploadLogsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When closed, this repeats the requested offset without acknowledging the batch.
	NextOffset int64 `protobuf:"varint,1,opt,name=next_offset,json=nextOffset,proto3" json:"next_offset,omitempty"`
	// A closed or truncated Gitea operation no longer accepts additional logs.
	Closed        bool `protobuf:"varint,2,opt,name=closed,proto3" json:"closed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadLogsResponse) Reset() {
	*x = UploadLogsResponse{}
	mi := &file_agent_v1_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadLogsResponse) ProtoMessage() {}

func (x *UploadLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadLogsResponse.ProtoReflect.Descriptor instead.
func (*UploadLogsResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_service_proto_rawDescGZIP(), []int{16}
}

func (x *UploadLogsResponse) GetNextOffset() int64 {
	if x != nil {
		return x.NextOffset
	}
	return 0
}

func (x *UploadLogsResponse) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

type AccessRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Types that are valid to be assigned to Frame:
	//
	//	*AccessRequest_Open
	//	*AccessRequest_Stdin
	//	*AccessRequest_Resize
	//	*AccessRequest_Signal
	//	*AccessRequest_StdinEof
	Frame         isAccessRequest_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessRequest) Reset() {
	*x = AccessRequest{}
	mi := &file_agent_v1_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRequest) ProtoMessage() {}

func (x *AccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRequest.ProtoReflect.Descriptor instead.
func (*AccessRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_service_proto_rawDescGZIP(), []int{17}
}

func (x *AccessRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *AccessRequest) GetFrame() isAccessRequest_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *AccessRequest) GetOpen() *OpenAccess {
	if x != nil {
		if x, ok := x.Frame.(*AccessRequest_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *AccessRequest) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Frame.(*AccessRequest_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *AccessRequest) GetResize() *TerminalSize {
	if x != nil {
		if x, ok := x.Frame.(*AccessRequest_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *AccessRequest) GetSignal() int32 {
	if x != nil {
		if x, ok := x.Frame.(*AccessRequest_Signal); ok {
			return x.Signal
		}
	}
	return 0
}

func (x *AccessRequest) GetStdinEof() bool {
	if x != nil {
		if x, ok := x.Frame.(*AccessRequest_StdinEof); ok {
			return x.StdinEof
		}
	}
	return false
}

type isAccessRequest_Frame interface {
	isAccessRequest_Frame()
}

type AccessRequest_Open struct {
	Open *OpenAccess `protobuf:"bytes,2,opt,name=open,proto3,oneof"`
}

type AccessRequest_Stdin struct {
	Stdin []byte `protobuf:"bytes,3,opt,name=stdin,proto3,oneof"`
}

type AccessRequest_Resize struct {
	Resize *TerminalSize `protobuf:"bytes,4,opt,name=resize,proto3,oneof"`
}

type AccessRequest_Signal struct {
	Signal int32 `protobuf:"varint,5,opt,name=signal,proto3,oneof"`
}

type AccessRequest_StdinEof struct {
	StdinEof bool `protobuf:"varint,6,opt,name=stdin_eof,json=stdinEof,proto3,oneof"`
}

func (*AccessRequest_Open) isAccessRequest_Frame() {}

func (*AccessRequest_Stdin) isAccessRequest_Frame() {}

func (*AccessRequest_Resize) isAccessRequest_Frame() {}

func (*AccessRequest_Signal) isAccessRequest_Frame() {}

func (*AccessRequest_StdinEof) isAccessRequest_Frame() {}

type OpenAccess struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Signed by Manager; binds site, Runtime, Pod, target version and capability.
	Ticket string `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	// Types that are valid to be assigned to Capability:
	//
	//	*OpenAccess_Terminal
	//	*OpenAccess_Command
	//	*OpenAccess_Sftp
	//	*OpenAccess_Endpoint
	//	*OpenAccess_Tcp
	Capability    isOpenAccess_Capability `protobuf_oneof:"capability"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAccess) Reset() {
	*x = OpenAccess{}
	mi := &file_agent_v1_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAccess) ProtoMessage() {}

func (x *OpenAccess) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAccess.ProtoReflect.Descriptor instead.
func (*OpenAccess) Descriptor() ([]byte, []int) {
	return file_agent_v1_service_proto_rawDescGZIP(), []int{18}
}

func (x *OpenAccess) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

func (x *OpenAccess) GetCapability() isOpenAccess_Capability {
	if x != nil {
		return x.Capability
	}
	return nil
}

func (x *OpenAccess) GetTerminal() *Terminal {
	if x != nil {
		if x, ok := x.Capability.(*OpenAccess_Terminal); ok {
			return x.Terminal
		}
	}
	return nil
}

func (x *OpenAccess) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Capability.(*OpenAccess_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *OpenAccess) GetSftp() *SFTP {
	if x != nil {
		if x, ok := x.Capability.(*OpenAccess_Sftp); ok {
			return x.Sftp
		}
	}
	return nil
}

func (x *OpenAccess) GetEndpoint() *Endpoint {
	if x != nil {
		if x, ok := x.Capability.(*OpenAccess_Endpoint); ok {
			return x.Endpoint
		}
	}
	return nil
}

func (x *OpenAccess) GetTcp() *LoopbackTCP {
	if x != nil {
		if x, ok := x.Capability.(*OpenAccess_Tcp); ok {
			return x.Tcp
		}
	}
	return nil
}

type isOpenAccess_Capability interface {
	isOpenAccess_Capability()
}

type OpenAccess_Terminal struct {
	Terminal *Terminal `protobuf:"bytes,2,opt,name=terminal,proto3,oneof"`
}

type OpenAccess_Command struct {
	Command *Command `protobuf:"bytes,3,opt,name=command,proto3,oneof"`
}

type OpenAccess_Sftp struct {
	Sftp *SFTP `protobuf:"bytes,4,opt,name=sftp,proto3,oneof"`
}

type OpenAccess_Endpoint struct {
	Endpoint *Endpoint `protobuf:"bytes,5,opt,name=endpoint,proto3,oneof"`
}

type OpenAccess_Tcp struct {
	Tcp *LoopbackTCP `protobuf:"bytes,6,opt,name=tcp,proto3,oneof"`
}

func (*OpenAccess_Terminal) isOpenAccess_Capability() {}

func (*OpenAccess_Command) isOpenAccess_Capability() {}

func (*OpenAccess_Sftp) isOpenAccess_Capability() {}

func (*OpenAccess_Endpoint) isOpenAccess_Capability() {}

func (*OpenAccess_Tcp) isOpenAccess_Capability() {}

// AccessTicketClaims is signed by Manager and verified by the current Agent.
type AccessTicketClaims struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	SiteUid         string                 `protobuf:"bytes,2,opt,name=site_uid,json=siteUid,proto3" json:"site_uid,omitempty"`
	ResourceUid     string                 `protobuf:"bytes,3,opt,name=resource_uid,json=resourceUid,proto3" json:"resource_uid,omitempty"`
	RuntimeUuid     string                 `protobuf:"bytes,4,opt,name=runtime_uuid,json=runtimeUuid,proto3" json:"runtime_uuid,omitempty"`
	PodUid          string                 `protobuf:"bytes,5,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	TargetVersion   int64                  `protobuf:"varint,6,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	Capability      AccessCapability       `protobuf:"varint,7,opt,name=capability,proto3,enum=agent.v1.AccessCapability" json:"capability,omitempty"`
	EndpointId      string                 `protobuf:"bytes,8,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	ExpiresUnix     int64                  `protobuf:"varint,9,opt,name=expires_unix,json=expiresUnix,proto3" json:"expires_unix,omitempty"`
	Nonce           []byte                 `protobuf:"bytes,10,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AccessTicketClaims) Reset() {
	*x = AccessTicketClaims{}
	mi := &file_agent_v1_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessTicketClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessTicketClaims) ProtoMessage() {}

func (x *AccessTicketClaims) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessTicketClaims.ProtoReflect.Descriptor instead.
func (*AccessTicketClaims) Descriptor() ([]byte, []int) {
	return file_agent_v1_service_proto_rawDescGZIP(), []int{19}
}

func (x *AccessTicketClaims) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *AccessTicketClaims) GetSiteUid() string {
	if x != nil {
		return x.SiteUid
	}
	return ""
}

func (x *AccessTicketClaims) GetResourceUid() string {
	if x != nil {
		return x.ResourceUid
	}
	return ""
}

func (x *AccessTicketClaims) GetRuntimeUuid() string {
	if x != nil {
		return x.RuntimeUuid
	}
	return ""
}

func (x *AccessTicketClaims) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *AccessTicketClaims) GetTargetVersion() int64 {
	if x != nil {
		return x.TargetVersion
	}
	return 0
}

func (x *AccessTicketClaims) GetCapability() AccessCapability {
	if x != nil {
		return x.Capability
	}
	return AccessCapability_ACCESS_CAPABILITY_UNSPECIFIED
}

func (x *AccessTicketClaims) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *AccessTicketClaims) GetExpiresUnix() int64 {
	if x != nil {
		return x.ExpiresUnix
	}
	return 0
}

func (x *AccessTicketClaims) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type Terminal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          string                 `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	Size          *TerminalSize          `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Terminal) Reset() {
	*x = Terminal{}
	mi := &file_agent_v1_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Terminal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Terminal) ProtoMessage() {}

func (x *Terminal) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Terminal.ProtoReflect.Descriptor instead.
func (*Terminal) Descriptor() ([]byte, []int) {
	return file_agent_v1_service_proto_rawDescGZIP(), []int{20}
}

func (x *Terminal) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *Terminal) GetSize() *TerminalSize {
	if x != nil {
		return x.Size
	}
	return nil
}

type TerminalSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       uint32                 `protobuf:"varint,1,opt,name=columns,proto3" json:"columns,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalSize) Reset() {
	*x = TerminalSize{}
	mi := &file_agent_v1_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalSize) ProtoMessage() {}

func (x *TerminalSize) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalSize.ProtoReflect.Descriptor instead.
func (*TerminalSize) Descriptor() ([]byte, []int) {
	return file_agent_v1_service_proto_rawDescGZIP(), []int{21}
}

func (x *TerminalSize) GetColumns() uint32 {
	if x != nil {
		return x.Columns
	}
	return 0
}

func (x *TerminalSize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SSH exec commands are evaluated by the selected user's login shell.
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// terminal is present when the SSH exec request allocated a PTY.
	Terminal      *Terminal `protobuf:"bytes,2,opt,name=terminal,proto3" json:"terminal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_agent_v1_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_agent_v1_service_proto_rawDescGZIP(), []int{22}
}

func (x *Command) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Command) GetTerminal() *Terminal {
	if x != nil {
		return x.Terminal
	}
	return nil
}

type SFTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SFTP) Reset() {
	*x = SFTP{}
	mi := &file_agent_v1_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SFTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SFTP) ProtoMessage() {}

func (x *SFTP) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SFTP.ProtoReflect.Descriptor instead.
func (*SFTP) Descriptor() ([]byte, []int) {
	return file_agent_v1_service_proto_rawDescGZIP(), []int{23}
}

type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_agent_v1_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_agent_v1_service_proto_rawDescGZIP(), []int{24}
}

func (x *Endpoint) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

type LoopbackTCP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          uint32                 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoopbackTCP) Reset() {
	*x = LoopbackTCP{}
	mi := &file_agent_v1_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoopbackTCP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoopbackTCP) ProtoMessage() {}

func (x *LoopbackTCP) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoopbackTCP.ProtoReflect.Descriptor instead.
func (*LoopbackTCP) Descriptor() ([]byte, []int) {
	return file_agent_v1_service_proto_rawDescGZIP(), []int{25}
}

func (x *LoopbackTCP) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type AccessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*AccessResponse_Accepted
	//	*AccessResponse_Stdout
	//	*AccessResponse_Stderr
	//	*AccessResponse_ExitStatus
	Frame         isAccessResponse_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessResponse) Reset() {
	*x = AccessResponse{}
	mi := &file_agent_v1_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessResponse) ProtoMessage() {}

func (x *AccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessResponse.ProtoReflect.Descriptor instead.
func (*AccessResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_service_proto_rawDescGZIP(), []int{26}
}

func (x *AccessResponse) GetFrame() isAccessResponse_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *AccessResponse) GetAccepted() bool {
	if x != nil {
		if x, ok := x.Frame.(*AccessResponse_Accepted); ok {
			return x.Accepted
		}
	}
	return false
}

func (x *AccessResponse) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Frame.(*AccessResponse_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *AccessResponse) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Frame.(*AccessResponse_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *AccessResponse) GetExitStatus() int32 {
	if x != nil {
		if x, ok := x.Frame.(*AccessResponse_ExitStatus); ok {
			return x.ExitStatus
		}
	}
	return 0
}

type isAccessResponse_Frame interface {
	isAccessResponse_Frame()
}

type AccessResponse_Accepted struct {
	Accepted bool `protobuf:"varint,1,opt,name=accepted,proto3,oneof"`
}

type AccessResponse_Stdout struct {
	Stdout []byte `protobuf:"bytes,2,opt,name=stdout,proto3,oneof"`
}

type AccessResponse_Stderr struct {
	Stderr []byte `protobuf:"bytes,3,opt,name=stderr,proto3,oneof"`
}

type AccessResponse_ExitStatus struct {
	ExitStatus int32 `protobuf:"varint,4,opt,name=exit_status,json=exitStatus,proto3,oneof"`
}

func (*AccessResponse_Accepted) isAccessResponse_Frame() {}

func (*AccessResponse_Stdout) isAccessResponse_Frame() {}

func (*AccessResponse_Stderr) isAccessResponse_Frame() {}

func (*AccessResponse_ExitStatus) isAccessResponse_Frame() {}

var File_agent_v1_service_proto protoreflect.FileDescriptor

const file_agent_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x16agent/v1/service.proto\x12\bagent.v1\x1a\x18codespace/v1/types.proto\"N\n" +
	"!RuntimeEndpointServiceListRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\"a\n" +
	"\"RuntimeEndpointServiceListResponse\x12;\n" +
	"\tendpoints\x18\x01 \x03(\v2\x1d.codespace.v1.RuntimeEndpointR\tendpoints\"\x88\x01\n" +
	" RuntimeEndpointServiceSetRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x129\n" +
	"\bendpoint\x18\x02 \x01(\v2\x1d.codespace.v1.RuntimeEndpointR\bendpoint\"#\n" +
	"!RuntimeEndpointServiceSetResponse\"q\n" +
	"#RuntimeEndpointServiceDeleteRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1f\n" +
	"\vendpoint_id\x18\x02 \x01(\tR\n" +
	"endpointId\"&\n" +
	"$RuntimeEndpointServiceDeleteResponse\"\xe5\x01\n" +
	"\x0eControlRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12-\n" +
	"\x06report\x18\x04 \x01(\v2\x15.agent.v1.AgentReportR\x06report\x12>\n" +
	"\x1baccepted_operation_rversion\x18\x05 \x01(\x03R\x19acceptedOperationRversion\"\xc6\x02\n" +
	"\vAgentReport\x12-\n" +
	"\x12operation_rversion\x18\x01 \x01(\x03R\x11operationRversion\x12+\n" +
	"\x12git_ssh_public_key\x18\x02 \x01(\fR\x0fgitSshPublicKey\x121\n" +
	"\x06result\x18\x03 \x01(\v2\x19.agent.v1.OperationResultR\x06result\x12.\n" +
	"\x06target\x18\x04 \x01(\v2\x16.agent.v1.AccessTargetR\x06target\x12-\n" +
	"\x04boot\x18\x05 \x01(\v2\x19.codespace.v1.RuntimeBootR\x04boot\x12I\n" +
	"\x0eresource_usage\x18\x06 \x01(\v2\".codespace.v1.RuntimeResourceUsageR\rresourceUsage\"\x8d\x01\n" +
	"\x0fOperationResult\x12-\n" +
	"\x12operation_rversion\x18\x01 \x01(\x03R\x11operationRversion\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.codespace.v1.FinalStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x8e\x04\n" +
	"\x0fControlResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12A\n" +
	"\x1dpermit_valid_for_milliseconds\x18\x03 \x01(\x03R\x1apermitValidForMilliseconds\x12<\n" +
	"\toperation\x18\x04 \x01(\v2\x1e.codespace.v1.OperationPayloadR\toperation\x129\n" +
	"\x06access\x18\x05 \x01(\v2!.codespace.v1.RuntimeAccessBundleR\x06access\x12>\n" +
	"\x1backnowledged_result_version\x18\x06 \x01(\x03R\x19acknowledgedResultVersion\x12)\n" +
	"\x10cancel_execution\x18\a \x01(\bR\x0fcancelExecution\x122\n" +
	"\aruntime\x18\b \x01(\v2\x18.agent.v1.RuntimeOptionsR\aruntime\x126\n" +
	"\x17access_verification_key\x18\t \x01(\fR\x15accessVerificationKey\x12-\n" +
	"\x12operation_rversion\x18\n" +
	" \x01(\x03R\x11operationRversion\"g\n" +
	"\x0eRuntimeOptions\x12'\n" +
	"\x10git_ssh_key_type\x18\x01 \x01(\tR\rgitSshKeyType\x12,\n" +
	"\x05cache\x18\x02 \x01(\v2\x16.agent.v1.RuntimeCacheR\x05cache\"\xfa\x02\n" +
	"\fRuntimeCache\x12%\n" +
	"\x0ebuild_registry\x18\x01 \x01(\tR\rbuildRegistry\x12\x1f\n" +
	"\vbuild_scope\x18\x02 \x01(\tR\n" +
	"buildScope\x12=\n" +
	"\amirrors\x18\x03 \x03(\v2#.agent.v1.RuntimeCache.MirrorsEntryR\amirrors\x12I\n" +
	"\vcredentials\x18\x04 \x03(\v2'.agent.v1.RuntimeCache.CredentialsEntryR\vcredentials\x1a:\n" +
	"\fMirrorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a\\\n" +
	"\x10CredentialsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.agent.v1.RegistryCredentialR\x05value:\x028\x01\"L\n" +
	"\x12RegistryCredential\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xa8\x01\n" +
	"\fAccessTarget\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x120\n" +
	"\x14primary_container_id\x18\x02 \x01(\tR\x12primaryContainerId\x126\n" +
	"\tendpoints\x18\x03 \x03(\v2\x18.agent.v1.EndpointTargetR\tendpoints\x12\x14\n" +
	"\x05ready\x18\x04 \x01(\bR\x05ready\"\x82\x01\n" +
	"\x0eEndpointTarget\x129\n" +
	"\bendpoint\x18\x01 \x01(\v2\x1d.codespace.v1.RuntimeEndpointR\bendpoint\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\"\xb2\x01\n" +
	"\x11UploadLogsRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12-\n" +
	"\x12operation_rversion\x18\x02 \x01(\x03R\x11operationRversion\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12+\n" +
	"\x05lines\x18\x04 \x03(\v2\x15.codespace.v1.LogLineR\x05lines\"M\n" +
	"\x12UploadLogsResponse\x12\x1f\n" +
	"\vnext_offset\x18\x01 \x01(\x03R\n" +
	"nextOffset\x12\x16\n" +
	"\x06closed\x18\x02 \x01(\bR\x06closed\"\xf2\x01\n" +
	"\rAccessRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12*\n" +
	"\x04open\x18\x02 \x01(\v2\x14.agent.v1.OpenAccessH\x00R\x04open\x12\x16\n" +
	"\x05stdin\x18\x03 \x01(\fH\x00R\x05stdin\x120\n" +
	"\x06resize\x18\x04 \x01(\v2\x16.agent.v1.TerminalSizeH\x00R\x06resize\x12\x18\n" +
	"\x06signal\x18\x05 \x01(\x05H\x00R\x06signal\x12\x1d\n" +
	"\tstdin_eof\x18\x06 \x01(\bH\x00R\bstdinEofB\a\n" +
	"\x05frame\"\x96\x02\n" +
	"\n" +
	"OpenAccess\x12\x16\n" +
	"\x06ticket\x18\x01 \x01(\tR\x06ticket\x120\n" +
	"\bterminal\x18\x02 \x01(\v2\x12.agent.v1.TerminalH\x00R\bterminal\x12-\n" +
	"\acommand\x18\x03 \x01(\v2\x11.agent.v1.CommandH\x00R\acommand\x12$\n" +
	"\x04sftp\x18\x04 \x01(\v2\x0e.agent.v1.SFTPH\x00R\x04sftp\x120\n" +
	"\bendpoint\x18\x05 \x01(\v2\x12.agent.v1.EndpointH\x00R\bendpoint\x12)\n" +
	"\x03tcp\x18\x06 \x01(\v2\x15.agent.v1.LoopbackTCPH\x00R\x03tcpB\f\n" +
	"\n" +
	"capability\"\xf6\x02\n" +
	"\x12AccessTicketClaims\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x19\n" +
	"\bsite_uid\x18\x02 \x01(\tR\asiteUid\x12!\n" +
	"\fresource_uid\x18\x03 \x01(\tR\vresourceUid\x12!\n" +
	"\fruntime_uuid\x18\x04 \x01(\tR\vruntimeUuid\x12\x17\n" +
	"\apod_uid\x18\x05 \x01(\tR\x06podUid\x12%\n" +
	"\x0etarget_version\x18\x06 \x01(\x03R\rtargetVersion\x12:\n" +
	"\n" +
	"capability\x18\a \x01(\x0e2\x1a.agent.v1.AccessCapabilityR\n" +
	"capability\x12\x1f\n" +
	"\vendpoint_id\x18\b \x01(\tR\n" +
	"endpointId\x12!\n" +
	"\fexpires_unix\x18\t \x01(\x03R\vexpiresUnix\x12\x14\n" +
	"\x05nonce\x18\n" +
	" \x01(\fR\x05nonce\"J\n" +
	"\bTerminal\x12\x12\n" +
	"\x04term\x18\x01 \x01(\tR\x04term\x12*\n" +
	"\x04size\x18\x02 \x01(\v2\x16.agent.v1.TerminalSizeR\x04size\"<\n" +
	"\fTerminalSize\x12\x18\n" +
	"\acolumns\x18\x01 \x01(\rR\acolumns\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"S\n" +
	"\aCommand\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12.\n" +
	"\bterminal\x18\x02 \x01(\v2\x12.agent.v1.TerminalR\bterminal\"\x06\n" +
	"\x04SFTP\"+\n" +
	"\bEndpoint\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\"!\n" +
	"\vLoopbackTCP\x12\x12\n" +
	"\x04port\x18\x01 \x01(\rR\x04port\"\x8e\x01\n" +
	"\x0eAccessResponse\x12\x1c\n" +
	"\baccepted\x18\x01 \x01(\bH\x00R\baccepted\x12\x18\n" +
	"\x06stdout\x18\x02 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x03 \x01(\fH\x00R\x06stderr\x12!\n" +
	"\vexit_status\x18\x04 \x01(\x05H\x00R\n" +
	"exitStatusB\a\n" +
	"\x05frame*\xd4\x01\n" +
	"\x10AccessCapability\x12!\n" +
	"\x1dACCESS_CAPABILITY_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aACCESS_CAPABILITY_TERMINAL\x10\x01\x12\x1d\n" +
	"\x19ACCESS_CAPABILITY_COMMAND\x10\x02\x12\x1a\n" +
	"\x16ACCESS_CAPABILITY_SFTP\x10\x03\x12\x1e\n" +
	"\x1aACCESS_CAPABILITY_ENDPOINT\x10\x04\x12\"\n" +
	"\x1eACCESS_CAPABILITY_LOOPBACK_TCP\x10\x052\xa2\x01\n" +
	"\x13AgentControlService\x12B\n" +
	"\aControl\x12\x18.agent.v1.ControlRequest\x1a\x19.agent.v1.ControlResponse(\x010\x01\x12G\n" +
	"\n" +
	"UploadLogs\x12\x1b.agent.v1.UploadLogsRequest\x1a\x1c.agent.v1.UploadLogsResponse2U\n" +
	"\x12AgentAccessService\x12?\n" +
	"\x06Access\x12\x17.agent.v1.AccessRequest\x1a\x18.agent.v1.AccessResponse(\x010\x012\xc4\x02\n" +
	"\x16RuntimeEndpointService\x12a\n" +
	"\x04List\x12+.agent.v1.RuntimeEndpointServiceListRequest\x1a,.agent.v1.RuntimeEndpointServiceListResponse\x12^\n" +
	"\x03Set\x12*.agent.v1.RuntimeEndpointServiceSetRequest\x1a+.agent.v1.RuntimeEndpointServiceSetResponse\x12g\n" +
	"\x06Delete\x12-.agent.v1.RuntimeEndpointServiceDeleteRequest\x1a..agent.v1.RuntimeEndpointServiceDeleteResponseB3Z1gitea.dev/codespace/internal/rpc/agent/v1;agentv1b\x06proto3"

var (
	file_agent_v1_service_proto_rawDescOnce sync.Once
	file_agent_v1_service_proto_rawDescData []byte
)

func file_agent_v1_service_proto_rawDescGZIP() []byte {
	file_agent_v1_service_proto_rawDescOnce.Do(func() {
		file_agent_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_service_proto_rawDesc), len(file_agent_v1_service_proto_rawDesc)))
	})
	return file_agent_v1_service_proto_rawDescData
}

var file_agent_v1_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_agent_v1_service_proto_goTypes = []any{
	(AccessCapability)(0),                        // 0: agent.v1.AccessCapability
	(*RuntimeEndpointServiceListRequest)(nil),    // 1: agent.v1.RuntimeEndpointServiceListRequest
	(*RuntimeEndpointServiceListResponse)(nil),   // 2: agent.v1.RuntimeEndpointServiceListResponse
	(*RuntimeEndpointServiceSetRequest)(nil),     // 3: agent.v1.RuntimeEndpointServiceSetRequest
	(*RuntimeEndpointServiceSetResponse)(nil),    // 4: agent.v1.RuntimeEndpointServiceSetResponse
	(*RuntimeEndpointServiceDeleteRequest)(nil),  // 5: agent.v1.RuntimeEndpointServiceDeleteRequest
	(*RuntimeEndpointServiceDeleteResponse)(nil), // 6: agent.v1.RuntimeEndpointServiceDeleteResponse
	(*ControlRequest)(nil),                       // 7: agent.v1.ControlRequest
	(*AgentReport)(nil),                          // 8: agent.v1.AgentReport
	(*OperationResult)(nil),                      // 9: agent.v1.OperationResult
	(*ControlResponse)(nil),                      // 10: agent.v1.ControlResponse
	(*RuntimeOptions)(nil),                       // 11: agent.v1.RuntimeOptions
	(*RuntimeCache)(nil),                         // 12: agent.v1.RuntimeCache
	(*RegistryCredential)(nil),                   // 13: agent.v1.RegistryCredential
	(*AccessTarget)(nil),                         // 14: agent.v1.AccessTarget
	(*EndpointTarget)(nil),                       // 15: agent.v1.EndpointTarget
	(*UploadLogsRequest)(nil),                    // 16: agent.v1.UploadLogsRequest
	(*UploadLogsResponse)(nil),                   // 17: agent.v1.UploadLogsResponse
	(*AccessRequest)(nil),                        // 18: agent.v1.AccessRequest
	(*OpenAccess)(nil),                           // 19: agent.v1.OpenAccess
	(*AccessTicketClaims)(nil),                   // 20: agent.v1.AccessTicketClaims
	(*Terminal)(nil),                             // 21: agent.v1.Terminal
	(*TerminalSize)(nil),                         // 22: agent.v1.TerminalSize
	(*Command)(nil),                              // 23: agent.v1.Command
	(*SFTP)(nil),                                 // 24: agent.v1.SFTP
	(*Endpoint)(nil),                             // 25: agent.v1.Endpoint
	(*LoopbackTCP)(nil),                          // 26: agent.v1.LoopbackTCP
	(*AccessResponse)(nil),                       // 27: agent.v1.AccessResponse
	nil,                                          // 28: agent.v1.RuntimeCache.MirrorsEntry
	nil,                                          // 29: agent.v1.RuntimeCache.CredentialsEntry
	(*v1.RuntimeEndpoint)(nil),                   // 30: codespace.v1.RuntimeEndpoint
	(*v1.RuntimeBoot)(nil),                       // 31: codespace.v1.RuntimeBoot
	(*v1.RuntimeResourceUsage)(nil),              // 32: codespace.v1.RuntimeResourceUsage
	(v1.FinalStatus)(0),                          // 33: codespace.v1.FinalStatus
	(*v1.OperationPayload)(nil),                  // 34: codespace.v1.OperationPayload
	(*v1.RuntimeAccessBundle)(nil),               // 35: codespace.v1.RuntimeAccessBundle
	(*v1.LogLine)(nil),                           // 36: codespace.v1.LogLine
}
var file_agent_v1_service_proto_depIdxs = []int32{
	30, // 0: agent.v1.RuntimeEndpointServiceListResponse.endpoints:type_name -> codespace.v1.RuntimeEndpoint
	30, // 1: agent.v1.RuntimeEndpointServiceSetRequest.endpoint:type_name -> codespace.v1.RuntimeEndpoint
	8,  // 2: agent.v1.ControlRequest.report:type_name -> agent.v1.AgentReport
	9,  // 3: agent.v1.AgentReport.result:type_name -> agent.v1.OperationResult
	14, // 4: agent.v1.AgentReport.target:type_name -> agent.v1.AccessTarget
	31, // 5: agent.v1.AgentReport.boot:type_name -> codespace.v1.RuntimeBoot
	32, // 6: agent.v1.AgentReport.resource_usage:type_name -> codespace.v1.RuntimeResourceUsage
	33, // 7: agent.v1.OperationResult.status:type_name -> codespace.v1.FinalStatus
	34, // 8: agent.v1.ControlResponse.operation:type_name -> codespace.v1.OperationPayload
	35, // 9: agent.v1.ControlResponse.access:type_name -> codespace.v1.RuntimeAccessBundle
	11, // 10: agent.v1.ControlResponse.runtime:type_name -> agent.v1.RuntimeOptions
	12, // 11: agent.v1.RuntimeOptions.cache:type_name -> agent.v1.RuntimeCache
	28, // 12: agent.v1.RuntimeCache.mirrors:type_name -> agent.v1.RuntimeCache.MirrorsEntry
	29, // 13: agent.v1.RuntimeCache.credentials:type_name -> agent.v1.RuntimeCache.CredentialsEntry
	15, // 14: agent.v1.AccessTarget.endpoints:type_name -> agent.v1.EndpointTarget
	30, // 15: agent.v1.EndpointTarget.endpoint:type_name -> codespace.v1.RuntimeEndpoint
	36, // 16: agent.v1.UploadLogsRequest.lines:type_name -> codespace.v1.LogLine
	19, // 17: agent.v1.AccessRequest.open:type_name -> agent.v1.OpenAccess
	22, // 18: agent.v1.AccessRequest.resize:type_name -> agent.v1.TerminalSize
	21, // 19: agent.v1.OpenAccess.terminal:type_name -> agent.v1.Terminal
	23, // 20: agent.v1.OpenAccess.command:type_name -> agent.v1.Command
	24, // 21: agent.v1.OpenAccess.sftp:type_name -> agent.v1.SFTP
	25, // 22: agent.v1.OpenAccess.endpoint:type_name -> agent.v1.Endpoint
	26, // 23: agent.v1.OpenAccess.tcp:type_name -> agent.v1.LoopbackTCP
	0,  // 24: agent.v1.AccessTicketClaims.capability:type_name -> agent.v1.AccessCapability
	22, // 25: agent.v1.Terminal.size:type_name -> agent.v1.TerminalSize
	21, // 26: agent.v1.Command.terminal:type_name -> agent.v1.Terminal
	13, // 27: agent.v1.RuntimeCache.CredentialsEntry.value:type_name -> agent.v1.RegistryCredential
	7,  // 28: agent.v1.AgentControlService.Control:input_type -> agent.v1.ControlRequest
	16, // 29: agent.v1.AgentControlService.UploadLogs:input_type -> agent.v1.UploadLogsRequest
	18, // 30: agent.v1.AgentAccessService.Access:input_type -> agent.v1.AccessRequest
	1,  // 31: agent.v1.RuntimeEndpointService.List:input_type -> agent.v1.RuntimeEndpointServiceListRequest
	3,  // 32: agent.v1.RuntimeEndpointService.Set:input_type -> agent.v1.RuntimeEndpointServiceSetRequest
	5,  // 33: agent.v1.RuntimeEndpointService.Delete:input_type -> agent.v1.RuntimeEndpointServiceDeleteRequest
	10, // 34: agent.v1.AgentControlService.Control:output_type -> agent.v1.ControlResponse
	17, // 35: agent.v1.AgentControlService.UploadLogs:output_type -> agent.v1.UploadLogsResponse
	27, // 36: agent.v1.AgentAccessService.Access:output_type -> agent.v1.AccessResponse
	2,  // 37: agent.v1.RuntimeEndpointService.List:output_type -> agent.v1.RuntimeEndpointServiceListResponse
	4,  // 38: agent.v1.RuntimeEndpointService.Set:output_type -> agent.v1.RuntimeEndpointServiceSetResponse
	6,  // 39: agent.v1.RuntimeEndpointService.Delete:output_type -> agent.v1.RuntimeEndpointServiceDeleteResponse
	34, // [34:40] is the sub-list for method output_type
	28, // [28:34] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_agent_v1_service_proto_init() }
func file_agent_v1_service_proto_init() {
	if File_agent_v1_service_proto != nil {
		return
	}
	file_agent_v1_service_proto_msgTypes[17].OneofWrappers = []any{
		(*AccessRequest_Open)(nil),
		(*AccessRequest_Stdin)(nil),
		(*AccessRequest_Resize)(nil),
		(*AccessRequest_Signal)(nil),
		(*AccessRequest_StdinEof)(nil),
	}
	file_agent_v1_service_proto_msgTypes[18].OneofWrappers = []any{
		(*OpenAccess_Terminal)(nil),
		(*OpenAccess_Command)(nil),
		(*OpenAccess_Sftp)(nil),
		(*OpenAccess_Endpoint)(nil),
		(*OpenAccess_Tcp)(nil),
	}
	file_agent_v1_service_proto_msgTypes[26].OneofWrappers = []any{
		(*AccessResponse_Accepted)(nil),
		(*AccessResponse_Stdout)(nil),
		(*AccessResponse_Stderr)(nil),
		(*AccessResponse_ExitStatus)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_service_proto_rawDesc), len(file_agent_v1_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_agent_v1_service_proto_goTypes,
		DependencyIndexes: file_agent_v1_service_proto_depIdxs,
		EnumInfos:         file_agent_v1_service_proto_enumTypes,
		MessageInfos:      file_agent_v1_service_proto_msgTypes,
	}.Build()
	File_agent_v1_service_proto = out.File
	file_agent_v1_service_proto_goTypes = nil
	file_agent_v1_service_proto_depIdxs = nil
}
