// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: component/v1/service.proto

package componentv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "gitea.dev/codespace/internal/rpc/component/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ComponentServiceName is the fully-qualified name of the ComponentService service.
	ComponentServiceName = "component.v1.ComponentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ComponentServiceGatewayControlProcedure is the fully-qualified name of the ComponentService's
	// GatewayControl RPC.
	ComponentServiceGatewayControlProcedure = "/component.v1.ComponentService/GatewayControl"
	// ComponentServiceAuthorizeGatewayProcedure is the fully-qualified name of the ComponentService's
	// AuthorizeGateway RPC.
	ComponentServiceAuthorizeGatewayProcedure = "/component.v1.ComponentService/AuthorizeGateway"
	// ComponentServiceIssueAgentAccessProcedure is the fully-qualified name of the ComponentService's
	// IssueAgentAccess RPC.
	ComponentServiceIssueAgentAccessProcedure = "/component.v1.ComponentService/IssueAgentAccess"
	// ComponentServiceCacheControlProcedure is the fully-qualified name of the ComponentService's
	// CacheControl RPC.
	ComponentServiceCacheControlProcedure = "/component.v1.ComponentService/CacheControl"
)

// ComponentServiceClient is a client for the component.v1.ComponentService service.
type ComponentServiceClient interface {
	// GatewayControl publishes Gateway activity and streams its current configuration and routes.
	GatewayControl(context.Context) *connect.BidiStreamForClient[v1.GatewayControlRequest, v1.GatewayControlResponse]
	// AuthorizeGateway delegates one user authorization decision to its Gitea site.
	AuthorizeGateway(context.Context, *connect.Request[v1.AuthorizeGatewayRequest]) (*connect.Response[v1.AuthorizeGatewayResponse], error)
	// IssueAgentAccess binds one short-lived ticket to the current Runtime Pod target.
	IssueAgentAccess(context.Context, *connect.Request[v1.IssueAgentAccessRequest]) (*connect.Response[v1.IssueAgentAccessResponse], error)
	// CacheControl publishes cache health and streams configuration and cleanup grants.
	CacheControl(context.Context) *connect.BidiStreamForClient[v1.CacheControlRequest, v1.CacheControlResponse]
}

// NewComponentServiceClient constructs a client for the component.v1.ComponentService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewComponentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ComponentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	componentServiceMethods := v1.File_component_v1_service_proto.Services().ByName("ComponentService").Methods()
	return &componentServiceClient{
		gatewayControl: connect.NewClient[v1.GatewayControlRequest, v1.GatewayControlResponse](
			httpClient,
			baseURL+ComponentServiceGatewayControlProcedure,
			connect.WithSchema(componentServiceMethods.ByName("GatewayControl")),
			connect.WithClientOptions(opts...),
		),
		authorizeGateway: connect.NewClient[v1.AuthorizeGatewayRequest, v1.AuthorizeGatewayResponse](
			httpClient,
			baseURL+ComponentServiceAuthorizeGatewayProcedure,
			connect.WithSchema(componentServiceMethods.ByName("AuthorizeGateway")),
			connect.WithClientOptions(opts...),
		),
		issueAgentAccess: connect.NewClient[v1.IssueAgentAccessRequest, v1.IssueAgentAccessResponse](
			httpClient,
			baseURL+ComponentServiceIssueAgentAccessProcedure,
			connect.WithSchema(componentServiceMethods.ByName("IssueAgentAccess")),
			connect.WithClientOptions(opts...),
		),
		cacheControl: connect.NewClient[v1.CacheControlRequest, v1.CacheControlResponse](
			httpClient,
			baseURL+ComponentServiceCacheControlProcedure,
			connect.WithSchema(componentServiceMethods.ByName("CacheControl")),
			connect.WithClientOptions(opts...),
		),
	}
}

// componentServiceClient implements ComponentServiceClient.
type componentServiceClient struct {
	gatewayControl   *connect.Client[v1.GatewayControlRequest, v1.GatewayControlResponse]
	authorizeGateway *connect.Client[v1.AuthorizeGatewayRequest, v1.AuthorizeGatewayResponse]
	issueAgentAccess *connect.Client[v1.IssueAgentAccessRequest, v1.IssueAgentAccessResponse]
	cacheControl     *connect.Client[v1.CacheControlRequest, v1.CacheControlResponse]
}

// GatewayControl calls component.v1.ComponentService.GatewayControl.
func (c *componentServiceClient) GatewayControl(ctx context.Context) *connect.BidiStreamForClient[v1.GatewayControlRequest, v1.GatewayControlResponse] {
	return c.gatewayControl.CallBidiStream(ctx)
}

// AuthorizeGateway calls component.v1.ComponentService.AuthorizeGateway.
func (c *componentServiceClient) AuthorizeGateway(ctx context.Context, req *connect.Request[v1.AuthorizeGatewayRequest]) (*connect.Response[v1.AuthorizeGatewayResponse], error) {
	return c.authorizeGateway.CallUnary(ctx, req)
}

// IssueAgentAccess calls component.v1.ComponentService.IssueAgentAccess.
func (c *componentServiceClient) IssueAgentAccess(ctx context.Context, req *connect.Request[v1.IssueAgentAccessRequest]) (*connect.Response[v1.IssueAgentAccessResponse], error) {
	return c.issueAgentAccess.CallUnary(ctx, req)
}

// CacheControl calls component.v1.ComponentService.CacheControl.
func (c *componentServiceClient) CacheControl(ctx context.Context) *connect.BidiStreamForClient[v1.CacheControlRequest, v1.CacheControlResponse] {
	return c.cacheControl.CallBidiStream(ctx)
}

// ComponentServiceHandler is an implementation of the component.v1.ComponentService service.
type ComponentServiceHandler interface {
	// GatewayControl publishes Gateway activity and streams its current configuration and routes.
	GatewayControl(context.Context, *connect.BidiStream[v1.GatewayControlRequest, v1.GatewayControlResponse]) error
	// AuthorizeGateway delegates one user authorization decision to its Gitea site.
	AuthorizeGateway(context.Context, *connect.Request[v1.AuthorizeGatewayRequest]) (*connect.Response[v1.AuthorizeGatewayResponse], error)
	// IssueAgentAccess binds one short-lived ticket to the current Runtime Pod target.
	IssueAgentAccess(context.Context, *connect.Request[v1.IssueAgentAccessRequest]) (*connect.Response[v1.IssueAgentAccessResponse], error)
	// CacheControl publishes cache health and streams configuration and cleanup grants.
	CacheControl(context.Context, *connect.BidiStream[v1.CacheControlRequest, v1.CacheControlResponse]) error
}

// NewComponentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewComponentServiceHandler(svc ComponentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	componentServiceMethods := v1.File_component_v1_service_proto.Services().ByName("ComponentService").Methods()
	componentServiceGatewayControlHandler := connect.NewBidiStreamHandler(
		ComponentServiceGatewayControlProcedure,
		svc.GatewayControl,
		connect.WithSchema(componentServiceMethods.ByName("GatewayControl")),
		connect.WithHandlerOptions(opts...),
	)
	componentServiceAuthorizeGatewayHandler := connect.NewUnaryHandler(
		ComponentServiceAuthorizeGatewayProcedure,
		svc.AuthorizeGateway,
		connect.WithSchema(componentServiceMethods.ByName("AuthorizeGateway")),
		connect.WithHandlerOptions(opts...),
	)
	componentServiceIssueAgentAccessHandler := connect.NewUnaryHandler(
		ComponentServiceIssueAgentAccessProcedure,
		svc.IssueAgentAccess,
		connect.WithSchema(componentServiceMethods.ByName("IssueAgentAccess")),
		connect.WithHandlerOptions(opts...),
	)
	componentServiceCacheControlHandler := connect.NewBidiStreamHandler(
		ComponentServiceCacheControlProcedure,
		svc.CacheControl,
		connect.WithSchema(componentServiceMethods.ByName("CacheControl")),
		connect.WithHandlerOptions(opts...),
	)
	return "/component.v1.ComponentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ComponentServiceGatewayControlProcedure:
			componentServiceGatewayControlHandler.ServeHTTP(w, r)
		case ComponentServiceAuthorizeGatewayProcedure:
			componentServiceAuthorizeGatewayHandler.ServeHTTP(w, r)
		case ComponentServiceIssueAgentAccessProcedure:
			componentServiceIssueAgentAccessHandler.ServeHTTP(w, r)
		case ComponentServiceCacheControlProcedure:
			componentServiceCacheControlHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedComponentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedComponentServiceHandler struct{}

func (UnimplementedComponentServiceHandler) GatewayControl(context.Context, *connect.BidiStream[v1.GatewayControlRequest, v1.GatewayControlResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("component.v1.ComponentService.GatewayControl is not implemented"))
}

func (UnimplementedComponentServiceHandler) AuthorizeGateway(context.Context, *connect.Request[v1.AuthorizeGatewayRequest]) (*connect.Response[v1.AuthorizeGatewayResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("component.v1.ComponentService.AuthorizeGateway is not implemented"))
}

func (UnimplementedComponentServiceHandler) IssueAgentAccess(context.Context, *connect.Request[v1.IssueAgentAccessRequest]) (*connect.Response[v1.IssueAgentAccessResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("component.v1.ComponentService.IssueAgentAccess is not implemented"))
}

func (UnimplementedComponentServiceHandler) CacheControl(context.Context, *connect.BidiStream[v1.CacheControlRequest, v1.CacheControlResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("component.v1.ComponentService.CacheControl is not implemented"))
}
